### PR TITLE
Carbon upgrade 10.48

### LINKED ISSUE #3074: [Repo] Upgrade Carbon to 10.48.0/7.48.1

### PR DESCRIPTION
**Pull request by kevinsperrine**
Closes #3074 

**Summary**

- upgrades carbon to 10.48.0/7.48.1

**Change List (commits, features, bugs, etc)**

- added onClick handler to div wrapping RowActionCells, because the click events for dismissing errors was no longer stopping propagation and was bubbling up to trigger the onRowClicked event. https://github.com/carbon-design-system/carbon/pull/9959
- previously the HotspotEditorDataSourceTab.tests were using `getAllByRole('button')[x]` and selecting an element directly from the array. Some of these calls needed to be changed to add `{name: 'XXX'}` to them, because the number of items with role="button" on the modal had changed.
- remove old styles from the table batch actions to ensure they show correctly with new changes, and remove extra 2px of space (toolbar being 50px instead of 48px tall).
- updated snapshots

**Acceptance Test (how to verify the PR)**

- ensure table row errors dismiss properly
- ensure batch actions appear when items selected

**Regression Test (how to make sure this PR doesn't break old functionality)**

- check stories for other breaks

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

**Review by davidicus — APPROVED** [review]

**Comment by bjornalm** [comment]
> ensure table row errors dismiss properly
Which story can I test that in?

**Review by bjornalm — COMMENTED** [review]
Nice work, code looks good. Just the wanna test the action dismiss error

**Comment by kevinsperrine** [comment]
> Nice work, code looks good. Just the wanna test the action dismiss error

This is where I tested it: Click on the tooltip icon to open the tooltip and see the dismiss button.
https://deploy-preview-3070--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table-tablebodyrow--row-actions-error

**Comment by bjornalm** [comment]
> > Nice work, code looks good. Just the wanna test the action dismiss error
> 
> This is where I tested it: Click on the tooltip icon to open the tooltip and see the dismiss button. https://deploy-preview-3070--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table-tablebodyrow--row-actions-error

Thanks. The `onClearRowError` is called when clicking the button but the actual error is not dismissed in the example. Should it?

**Comment by kevinsperrine** [comment]
> > > Nice work, code looks good. Just the wanna test the action dismiss error
> > 
> > 
> > This is where I tested it: Click on the tooltip icon to open the tooltip and see the dismiss button. https://deploy-preview-3070--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table-tablebodyrow--row-actions-error
> 
> Thanks. The `onClearRowError` is called when clicking the button but the actual error is not dismissed in the example. Should it?

No, there's no actual state management in it, it's up-to the consumer to dismiss it. We just want to ensure the `onClearRowError` is the only thing called..the removal of the stopPropagation in the carbon tooltip was allowing it to bubble all the way and trigger `onRowClicked`, too.

**Review by bjornalm — APPROVED** [review]

**Pull request merged**
