### PR TITLE
fix(date-time-picker): flatpickr 4.6.9 fix

### LINKED ISSUE #2868: [DateTimePicker] flatpickr version difference breaking absolute datetime picking
### What package is this for?

- [X] React
- [ ] Angular

### Describe the bug

After flatpickr version 4.6.1 changing preselected absolute DateTimePicker ranges is not possible.

### PR DESCRIPTION
**Pull request by kevinsperrine**
Closes #2868 

**Summary**

- Fixes the input focusing events so that versions of flatpickr newer than 4.6.1 can be used.

**Change List (commits, features, bugs, etc)**

- changed `focus()` events to `click()` events to properly set focus on "from" input or "to" inputs
- updated tests to confirm this behavior

**Acceptance Test (how to verify the PR)**

- You can change the selected range in the preselected absolute range story

**Regression Test (how to make sure this PR doesn't break old functionality)**

- keyboard navigation still works
- tests pass
- DateTimePicker works as expected in other stories

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

**Comment by kevinsperrine** [comment]
@davidicus I opened this against next, but it probably warrants being opened against master to make it into 8.6. Do you agree?

**Comment by kevinsperrine** [comment]
@davidicus Can you re-trigger netlify on this one, please?

**Comment by navjeets** [comment]
@kevinsperrine Is there an estimate by when can this PR be merged? It is a high priority for MAS 8.6

**Comment by kevinsperrine** [comment]
> @kevinsperrine Is there an estimate by when can this PR be merged? It is a high priority for MAS 8.6

@navjeets I'm going to close this out and re-open it against master, so that it makes it into DCUT. 2.146.0 is the latest release that we cut off, so you can pull it in as a patch version there. We'll get it in ASAP.

**Pull request closed without merging**
