### PR TITLE
fix(BarChartCard): use series for sample data generation

### PR DESCRIPTION
**Pull request by sstone2423**
**Summary**

- `series` was not being used to generate sample data in the dashboard preview which was leading to data items not matching correctly in the generation logic

**Change List (commits, features, bugs, etc)**

- Swapped sample data generation for dashboard previews to use series similar to the `isEditable` sample generation
  - This should really be rewritten to have a single generatedata function with a boolean for `isEditable` vs the `isPreview`
- Removed `hideHeader` boolean for custom cards as we shouldn't assume the user wants it
- Added a test to cover default card renders

**Acceptance Test (how to verify the PR)**

- Go to any DashboardEditor story, add a BarChartCard, select a time range, select a groupBy, select a data item, then see that the data renders correctly

### CODE REVIEW

**Review by JoelArmendariz — APPROVED** [review]
LGTM

**Review by davidicus — DISMISSED** [review]
Looks good but you are getting an error for not meeting threshold for testing. Once your test pass we can merge.

**Comment by scottdickerson** [comment]
@davidicus can you rereview this today?

**Review by scottdickerson — APPROVED** [review]
LGTM

**Pull request merged**
