### PR TITLE
fix(FlyoutMenu): add new prop triggerClassname

### LINKED ISSUE #3624: [FlyoutMenu] support new prop triggerClassName
### What package is this for?

- [x] React
- [ ] Angular

### Summary

We need to expose triggerClassName to set the outline:none on the .bx--tooltip__label for the FlyoutMenu Tooltip. Otherwise, it shows a build outlined dot under the FlyoutMenu button. 

image
image

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

_Carbon add-ons for Watson IoT is a collaborative system. We encourage teams to
build components and submit them for integration._

### PR DESCRIPTION
**Pull request by jessieyan**
Closes #3624 

**Summary**

- The `.bx--tooltip__label `has a blue outline with 0 pixels. It shows as a blue dot when tab focus on it.
- We need to expose triggerClassName to set the `outline:none` on the `.bx--tooltip__label` for the FlyoutMenu Tooltip. 

 
image
image

**Change List (commits, features, bugs, etc)**

- add prop triggerClassname in FlyoutMenu
- set triggerClassname in DateTimePickerV2

**Acceptance Test (how to verify the PR)**

- go to single select or range select story
- click tab in keyboard
- see focus will not move to a blue dot label under the dataTime Input

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

**Comment by davidicus** [comment]
Hey @jessieyan I am not seeing this dot in our storybook. Are you sure this is still necessary? Also I think we can scope this to our DateTimePicker in the DateTimePicker.scss stylesheet  and target the existing class without the need for additional props.

**Comment by jessieyan** [comment]
> 

@davidicus  It only happens when click Tab on keyboard. Do you see it here?

https://user-images.githubusercontent.com/24279794/199828772-8f755833-dd13-4ed3-8f68-3041e16a7809.mov

**Comment by davidicus** [comment]
Hey @jessieyan. What is this trigger component for? It does not seem to be necessary to open the dropdown. Is this something we can get rid of?

**Comment by jessieyan** [comment]
Hey @davidicus  

The trigger is located in <ToolTip> component in Carbon.  In <FlyOutMenu>, <Tooltip> is rendered as a child of < div class="iot--flyout-menu--tooltip-anchor>

image

image


In Carbon <Tooltip>, you'll see the `triggerClasses` are used for override the styles.  I didn't see a prop to not render the trigger.  `showIcon` prop is set to `false` here. 

image

**Comment by davidicus** [comment]
`.#{$iotPrefix}--flyout-menu .#{$prefix}--tooltip__label` should be sufficient to select this element without the need of having to add props and classnames.

**Review by davidicus — CHANGES_REQUESTED** [review]
Let's use existing classes to select this element.

**Comment by jessieyan** [comment]
Fixed in the scss file.

**Review by davidicus — APPROVED** [review]

**Pull request merged**
