### PR TITLE
style(simplepagination): fixed misaligned pagination footer

### PR DESCRIPTION
**Pull request by Ujjwal-UJ**
Closes #
- Related to https://github.ibm.com/wiotp/Maximo-Asset-Monitor/issues/3653 section 2

**Summary**

- footer of simple pagination is misaligned https://media.github.ibm.com/user/627/files/2caa0700-7eba-11ec-8f90-73ddb205f4b7

**Change List (commits, features, bugs, etc)**

- style(simplepagination): fixed misaligned pagination footer

**Acceptance Test (how to verify the PR)**

- Page Items should come in one line with Page No. on right side

**Regression Test (how to make sure this PR doesn't break old functionality)**

- tests here

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

**Comment by davidicus** [comment]
As I said in the last PR this goes against our style guide. You are able to achieve the style you want using the correct props surfaced for the component. 

Note the separation already in place in this image and [story](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-pagination-simplepagination--default) 
image

**Comment by davidicus** [comment]
If you do not want the arrow buttons to appear you can use the `maxPages` prop. You can control the text on the right by utilizing the `pageOfPagesText` function. I am closing this PR for now but if you feel that this does not address your issue please re-open.

**Comment by Ujjwal-UJ** [comment]
> As I said in the last PR this goes against our style guide. You are able to achieve the style you want using the correct props surfaced for the component.
> 
> Note the separation already in place in this image and [story](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-pagination-simplepagination--default) image

> There is no style props that can be passed into simple pagination, and we are using List component there it does not aligns properly due to responsiveness

**Comment by davidicus** [comment]
Looks like this use of the pagination for list is out of [spec](https://github.com/carbon-design-system/carbon-addons-iot-react/issues/3062). Could be something for Cynthia to bring up during our office hours.

**Comment by CynZhang** [comment]
@davidicus Just wanted to confirm my understanding of the issue here. The new spec suggests to reposition the page number indicator from the right to the left, and this footer component does not include the item count element which is what causes this misalignment issue?

**Pull request closed without merging**
