### PR TITLE
fix(dashboardeditor): hide value card font size setting

### PR DESCRIPTION
**Pull request by sstone2423**
**Summary**

- Hide the font size setting for ValueCards in the dashboard editor until https://github.com/carbon-design-system/carbon-addons-iot-react/issues/1892 is fixed

**Acceptance Test (how to verify the PR)**

- Go to any DashboardEditor story and see that the ValueCard font size setting is hidden

### CODE REVIEW

**Comment by JoelArmendariz** [comment]
I think maybe we should hide the tab completely, rather than having the option go to it and it being empty? I know it's temporary, but it could be strange to have an empty tab like that.

**Review by JoelArmendariz — APPROVED** [review]
Looks good!

**Review by scottdickerson — APPROVED** [review]
LGTM

**Pull request merged**
