### PR TITLE
feat(imagegallery): add delete option to modal

### PR DESCRIPTION
**Pull request by scottdickerson**
Closes #

**Summary**

- feat(imagegallerymodal): allow the deletion in the imagegallery inside the dashboard editor

**Change List (commits, features, bugs, etc)**

- feat(DashboardEditor): add onImageDelete callback and new i18n labels imageGalleryDeleteLabelText: PropTypes.string,
    imageGalleryDeleteModalLabelText: PropTypes.string,
    imageGalleryDeleteModalTitleText: PropTypes.func,
- feat(ImageGalleryModal): support deletion if onDelete is set

**Acceptance Test (how to verify the PR)**

- Verify deletion is possible inside the dashboard editor

### CODE REVIEW

**Comment by JoelArmendariz** [comment]
Deletion inside the `Add from gallery` modal doesn't seem to be working for me. 
Also, looks like there's a small styling bug with the selected blue border state losing the top side: 
Screen Shot 2020-12-11 at 11 40 40 AM

**Review by tay1orjones — COMMENTED** [review]
I think it's important that we retain the checkmark icon to denote that the card is selected. 

image


Perhaps the delete button could be overlaid the image in the bottom right corner of the card instead?

**Review by tay1orjones — APPROVED** [review]

**Review by JoelArmendariz — APPROVED** [review]
LGTM

**Pull request merged**
