### PR TITLE
fix(table): filter tag has wrong color on hover

### PR DESCRIPTION
**Pull request by Ritu-Thakur**
Closes : https://github.com/carbon-design-system/carbon-addons-iot-react/issues/3189

**Summary**

Filter tag has wrong color on hover

**Change List (commits, features, bugs, etc)**

Added "blue" type in the Table's tag

**Acceptance Test (how to verify the PR)**

Check Filter tag and hover over the "x" button:
https://deploy-preview-3226--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table-statefultable--stateful-table-with-advanced-filters

**Regression Test (how to make sure this PR doesn't break old functionality)**

- tests here

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

**Comment by bjornalm** [comment]
@Ritu-Thakur Is this one ready for review?

**Review by kevinsperrine — CHANGES_REQUESTED** [review]
Thanks, @Ritu-Thakur. These color changes are good, but Ben is also talking about the hover state for the close icon. You'll want to add another selector in that same block for `.#{$prefix}--tag__close-icon:hover` and set the appropriate color for the button, also.

**Comment by bjornalm** [comment]
> > @Ritu-Thakur Is this one ready for review?
> 
> @bjornalm Yes, but need input from you guys if this is the correct fix?

Great, we normally add the label "status: ready for review" to indicate that the PR is ready. I did that. It is not a requirement but it also helps if the section "Acceptance Test (how to verify the PR)" contains a link to the story in the PR preview where the fix can be tested.

**Comment by Ritu-Thakur** [comment]
I tried to find the exact color for close button in hover state, I found that $link-02 is the one we need:


image


But use of  doesn't work for me 👍 


  .#{$prefix}--tag__close-icon:hover {
    background-color: #a6c8ff;
  }

**Review by kevinsperrine — APPROVED** [review]
Nice work!

**Review by davidicus — APPROVED** [review]

**Comment by davidicus** [comment]
This is good but it is failing our visual regression test for Table. We will want to update these.

**Pull request merged**
