### PR TITLE
3331 table story and docs for data editing

### LINKED ISSUE #3331: [Table] story and docs for data editing
### What package is this for?

- [x] React
- [ ] Angular

### Summary

Add story and docs for data editing, part of https://github.com/carbon-design-system/carbon-addons-iot-react/issues/2820

**Additional context** Add any other context or screenshots about the feature
request here.

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

_Carbon add-ons for Watson IoT is a collaborative system. We encourage teams to
build components and submit them for integration._

### PR DESCRIPTION
**Pull request by bjornalm**
Closes #3331

**Summary**

Adding story and (improved) docs for data editing

**Change List (commits, features, bugs, etc)**

- new story
- new mdx file
- fixed issue with 

**Acceptance Test (how to verify the PR)**

- Test story https://deploy-preview-3397--carbon-addons-iot-react.netlify.app?path=/story/1-watson-iot-table--with-data-editing
- Verify docs https://deploy-preview-3397--carbon-addons-iot-react.netlify.app?path=/docs/1-watson-iot-table--with-data-editing

**Regression Test (how to make sure this PR doesn't break old functionality)**

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

**Review by davidicus — APPROVED** [review]
Looks good. @kevinsperrine I was unable to reproduce your error of not seeing the save button.

**Comment by kevinsperrine** [comment]
> Looks good. @kevinsperrine I was unable to reproduce your error of not seeing the save button.

@davidicus My bad. I forgot to include "Change to StatefulTable" in my repro steps. It works with Table, but the Save button is always disabled with the StatefulTable.

**Comment by bjornalm** [comment]
> * Change to StatefulTable
> * Edit row 2
> * change number to '5'
> * save still disabled

Nice catch. I think this is a design flaw of the StatefulTable's edit data features. Create https://github.com/carbon-design-system/carbon-addons-iot-react/pull/3405 and a workaround in the story to handle the issue. Also created issue https://github.com/carbon-design-system/carbon-addons-iot-react/issues/3406 to find a more permanent solution

**Review by kevinsperrine — APPROVED** [review]
Works now! Nice work-around.

**Pull request merged**
