### PR TITLE
Dashboard editor custom card side bar

### PR DESCRIPTION
**Pull request by JoelArmendariz**
**Summary**
Expands the support of CustomCard types in the dashboard editor to allow the consumer to specify what they want to render in both the content editor and the settings editor.

**Change List (commits, features, bugs, etc)**
 - Use two new properties on the payload of the `CUSTOM` card type (`renderEditContent` & `renderEditSettings`) to render custom editor elements.
 - Include the `icons` prop used in the `CardGalleryList` as a top level prop for use with the Custom card type.

**Acceptance Test (how to verify the PR)**
Go to the `DashboardEditor` `With custom card` story and see that there is a new type in the gallery list called `My custom type`. 
Verify that the custom content and settings editors on the right properly update the CustomCard content in the dashboard.

**Regression Test (how to make sure this PR doesn't break old functionality)**
Make sure the other defined cards still act as expected.

image

### CODE REVIEW

**Comment by scottdickerson** [comment]
You attached the DashboardEditor control callbacks to the actual card itself so that multiple different custom cards can be used in the DashboardEditor with different Content and Settings Panels (smart!), but does it actually work?  Can you extend the Dashboard Custom Card story to show these two types of custom cards in the gallery and verify that each one can use a different set of forms to edit?

**Comment by JoelArmendariz** [comment]
> @JoelArmendariz You attached the DashboardEditor control callbacks to the actual card itself so that multiple different custom cards can be used in the DashboardEditor with different Content and Settings Panels (smart!), but does it actually work? Can you extend the Dashboard Custom Card story to show these two types of custom cards in the gallery and verify that each one can use a different set of forms to edit?

@scottdickerson I have added a 2nd custom card to the story with its own edit panels. You can go into each and update them separately.

**Review by scottdickerson — APPROVED** [review]
LGTM

**Review by davidicus — APPROVED** [review]
Any ideas why those snapshots are changing for ImageCard and HeirarchyList

**Pull request merged**
