### PR TITLE
feat(errortable): add an error state to the table

### PR DESCRIPTION
**Pull request by herleraja**
Related to https://github.ibm.com/wiotp/Maximo-Asset-Monitor/issues/2330

**Summary**

- Display an error state on any table error messages

**Change List (commits, features, bugs, etc)**

- feat(ErrorTable): added to display the error state, with or without error state button and error state element
- feat(EmptyState): left-align the empty state in the table
- chore(codeowners): adding amritha raj to the code owners list

**Acceptance Test (how to verify the PR)**

- Able to display custom error component
image
- Able to display an error message without any error action button
image
- Able to display an error message with any error action button
image

**Regression Test (how to make sure this PR doesn't break old functionality)**

- table component should work without any issues.

### CODE REVIEW

**Review by sstone2423 — COMMENTED** [review]
I think the error state needs to be left aligned in case of tables that have a lot of columns with horizontal scrolling

For example,
Screen Shot 2021-05-17 at 11 15 02 AM

**Comment by herleraja** [comment]
> I think the error state needs to be left aligned in case of tables that have a lot of columns with horizontal scrolling
> 
> For example,
> Screen Shot 2021-05-17 at 11 15 02 AM

Should we always left align? because it's not good to have both centers align (if the number of columns is less) and left align if the number of columns more.

**Comment by sstone2423** [comment]
It seems like we should always left align in the table, but we can check with UX @CynZhang

**Review by kevinsperrine — APPROVED** [review]
Can you also add the new props to the README?

**Comment by herleraja** [comment]
@sstone2423 I have left align the empty state in the table.

**Review by bjornalm — CHANGES_REQUESTED** [review]
Nice work, but look at the RTL mode. Some issues with alignment there.

**Comment by davidicus** [comment]
@dianatran18 Do you have any guidance on whether to left align the error message or not for the scenario that @herleraja mentions above?

**Comment by herleraja** [comment]
> @dianatran18 Do you have any guidance on whether to left align the error message or not for the scenario that @herleraja mentions above?

Hey, @davidicus Here is some pattern that already defined.
https://www.carbondesignsystem.com/patterns/empty-states-pattern/

Also, I have some design input from @CynZhang.
image

image

**Comment by herleraja** [comment]
> Nice work, but look at the RTL mode. Some issues with alignment there.

Thanks for the heads up. I newer tested in RTL mode. Do you use any Chrome addon to test it ? Is there any sample demo (or example link) that I can use for testing?

**Comment by bjornalm** [comment]
> > Nice work, but look at the RTL mode. Some issues with alignment there.
> 
> Thanks for the heads up. I newer tested in RTL mode. Do you use any Chrome addon to test it ? Is there any sample demo (or example link) that I can use for testing?

There is an RTL tab in the Storybook addons panel that lets you toggle rtl mode
image

**Comment by dianatran18** [comment]
> @dianatran18 Do you have any guidance on whether to left align the error message or not for the scenario that @herleraja mentions above?

Hi sorry for the late reply. 

Yes we've defined the placement of empty states on data tables in our PAL here: https://pages.github.ibm.com/ai-applications/design/components/datatable/emptystates/#empty-state-placement

**Comment by herleraja** [comment]
@bjornalm I'm able to fix the empty state component itself, whereas the empty state in the table itself seems to be spooky (frankly speaking Table itself in RTL mood is spooky). 
image

image

**Review by scottdickerson — APPROVED** [review]
LGTM

**Review by davidicus — APPROVED** [review]

**Pull request merged**
