### PR TITLE
fix(header): make style changes to align with spec

### LINKED ISSUE #1710: [Header] fix small Issues with Header styles
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

There is a are a few tweaks that still need to be made to align our implementation with AI Application PAL spec. 
- All header icons are not centered to the rest of the content on the header
- Remove the reference to Watson IoT.

### Additional context
We have reported the alignment bug to carbon and tracking [here](https://github.com/carbon-design-system/carbon/issues/7090)

### PR DESCRIPTION
**Pull request by davidicus**
Closes #1710 

**Summary**

- Just a few style changes to align with the spec. 

**Change List (commits, features, bugs, etc)**

- Changed styles for _header.scss
- removed reference to Watson IoT from stories in Header.story.jsx

**Acceptance Test (how to verify the PR)**

- Open up header story and see that all the icons are centered with the text. Also notice the lack of Watson IoT in the header.

### CODE REVIEW

**Review by tay1orjones — APPROVED** [review]
Wow, good eye

**Review by bjornalm — APPROVED** [review]
Nice work

**Pull request merged**
