### PR TITLE
fix(datetimepicker): fix setting absolute value

### LINKED ISSUE #1592: [DateTimePicker] Absolute range not working
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

DateTimePicker range absolute select doesnt work when also have preset.
https://carbon-addons-iot-react.com/?path=/story/watson-iot-experimental-datetime-picker--selected-preset

### To Reproduce

1. Go to 'https://carbon-addons-iot-react.com/?path=/story/watson-iot-experimental-datetime-picker--selected-preset'
2. Click on 'Custom range'
3. Click on 'Absolute'
4. Try to have a range for absolute

### Expected behavior

Absolute selector should work with preset default and enable a range selector.

### Environment/versions:

- OS:  MacOS
- Browser:  chrome,
- `carbon-addons-iot-react` version:  `v2.115.0`]

### Additional context

image

### Specific timeline issues / requests

- ApplicationSuite release 8.2 (Oct)

### PR DESCRIPTION
**Pull request by davidicus**
Closes #1592 

**Summary**

Somewhere along the line we lost the ability to add an absolute value. This PR fixes this regression. 

**Change List (commits, features, bugs, etc)**

- Change in DateTimePicker.jsx

**Acceptance Test (how to verify the PR)**

- go to default story and click on custom. choose absolute and pick a date range. You will see the date range update.

### CODE REVIEW

**Comment by tay1orjones** [comment]
@davidicus did you have any success trying to cover this in a unit test? Understandable if this is something that needs to be tested in a real browser environment via Cypress #1203

**Review by tay1orjones — APPROVED** [review]
@davidicus did you have any success trying to cover this in a unit test? Understandable if this is something that needs to be tested in a real browser environment via Cypress #1203

**Review by bryancboyd — APPROVED** [review]
Looks good

**Comment by davidicus** [comment]
> @davidicus did you have any success trying to cover this in a unit test? Understandable if this is something that needs to be tested in a real browser environment via Cypress #1203

@tay1orjones I did not. I will try to tinker around with it some more but I think this is another one of the list of browser interactions we need Cypress to do well.

**Pull request merged**
