### PR TITLE
fix(overflow): removed default background color for button

### LINKED ISSUE #1852: [OverflowMenu] background color is not correct
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

Somewhere in the november sprint the overflow menu background color is now different. You can see the issue currently between master and next storybooks.

Invalid background color:
https://next.carbon-addons-iot-react.com/?path=/story/overflowmenu--basic

Valid background color:
https://carbon-addons-iot-react.com/?path=/story/overflowmenu--basic

image

### PR DESCRIPTION
**Pull request by marcJV**
Closes #1852

**Summary**

- Removed the background color from the overflow button

**Change List (commits, features, bugs, etc)**

- _overflow-menu.scss

**Acceptance Test (how to verify the PR)**

- head on over to ?path=/story/overflowmenu--basic and verify the background color was removed.
- Should look exactly like: https://carbon-addons-iot-react.com/?path=/story/overflowmenu--basic

### CODE REVIEW

**Review by sstone2423 — APPROVED** [review]
Nice. Did you find out why it happened? It seems like a band-aid fix

**Comment by tay1orjones** [comment]
Yeah, would be nice to know why this happened. There are some other differences. 

image


Left is master, right is next. There’s a missing `display: inline-block`, even though there’s also a `display: flex`. `appearance` is missing. We now have a `font-family` declaration whereas master doesn't. I fear we might need to sift through recent PR deploy previews in attempt to pin down when this was introduced 😣

**Comment by marcJV** [comment]
Narrowed it down to `v2.141.0-next.9` so far for the background color, still looking to see exactly what caused this and if this fixes all of the issues

**Comment by tay1orjones** [comment]
It sounds like this is a side effect of some duplicate/mismatching dependency versions of @carbon/colors and/or carbon-components through the @carbon/charts package.

I think we can merge this as a bandaid fix with an eye to take another look when we update carbon versions #1702

**Review by tay1orjones — APPROVED** [review]

**Pull request merged**
