### PR TITLE
chore(repo): replace node-sass with sass package

### LINKED ISSUE #2371: [Repo] Swap out node-sass for dart-sass
lib sass is being deprecated. The main package for sass is now the dart implementation. We should swap out for the new package in order to keep getting up to date sass features and to prepare for the Carbon major release which will make use of sass modules. 

- [x] remove `node-sass` and add `sass` package
- [x] check for any compilation errors

### PR DESCRIPTION
**Pull request by davidicus**
Closes #2371

**Summary**

Lib sass is deprecated and Carbon is moving to sass modules. To prepare this pr swaps out `node-sass` package for `sass` one. Swapping over to sass modules will be handled in another issue. 

**Change List (commits, features, bugs, etc)**

- removed `node-sass` and installed `sass`

**Acceptance Test (how to verify the PR)**

- All builds and test should pass. 

**Regression Test (how to make sure this PR doesn't break old functionality)**

- can check around the storybook to be sure no styles were changed. I went through all stories and did not notice any differences. Should be a clean 1 for 1 swap.

### CODE REVIEW

**Review by kevinsperrine — APPROVED** [review]
LGTM. I don't see any issues in the stories either. Just the rulebuilder thing you already opened an issue for.

**Comment by bjornalm** [comment]
I assume it was some kind of merge accident, but why was the packages/react/src/components/MapCard/storyFiles/data.json modified in this PR?

**Review by bjornalm — APPROVED** [review]
LGTM

**Comment by davidicus** [comment]
@bjornalm good catch. Not sure what that was but I have removed from PR

**Review by cal-smith — APPROVED** [review]
LGTM!

**Pull request merged**
