### PR TITLE
feat(dashboardeditor): duplicated card is placed next to the original card

### LINKED ISSUE #1764: [DashboardEditor] clone card action should place card next to original card
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

When cloning a card, the new card is placed at the end of the dashboard template, which could cause confusion as to where the newly cloned card went

### To Reproduce

1. Go to any DashboardEditor story
2. Add a card
3. Clone the card

### Expected behavior

Cloned card should render next to the current card

### Environment/versions:

- OS: MacOS
- Browser: chrome
- `carbon-addons-iot-react` version: ^2.141.0-next.3

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

November release

### PR DESCRIPTION
**Pull request by sstone2423**
Closes #1764

**Summary**

- Duplicating a card now places the new card next to the original card

**Acceptance Test (how to verify the PR)**

- Go to /?path=/story/watson-iot-experimental-dashboardeditor--with-initial-value , duplicate any card besides the last card and see that its placed next to the original card

### CODE REVIEW

**Review by herleraja — APPROVED** [review]
LGTM

**Comment by davidicus** [comment]
This looks good. Did you want the card to appear below it every time? It will copy the card directly below the original even if there is space beside it.

**Review by davidicus — APPROVED** [review]
LGTM. Just the one comment about the duplicate being added below the original card.

**Comment by sstone2423** [comment]
@davidicus Thats the current DashboardGrid behavior which got changed recently. All new cards get added vertically, which is probably also a bug

**Pull request merged**
