### PR TITLE
fix(table): increase min width for filterable column

### LINKED ISSUE #3387: [table] increase min width for filterable columns
### What package is this for?

- [x] React
- [ ] Angular

### Summary
There should always be text visible in the dropdowns of filterable columns, so we need to increase the column min width.

**Additional context** 
See discussion here 
https://github.com/carbon-design-system/carbon-addons-iot-react/issues/3231#issuecomment-1046976564

This is how it currently can look
image

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

_Carbon add-ons for Watson IoT is a collaborative system. We encourage teams to
build components and submit them for integration._

### PR DESCRIPTION
**Pull request by erzhan-temir-mamyrov**
Closes #3387 

**Summary**

- Increase min width for column from `62px` to `120px`
- Add text truncation for selected value in `ComboBox`

**Change List (commits, features, bugs, etc)**

- Change min width constant `MIN_COLUMN_WIDTH`
- Add css property for text truncation
- Update tests
- Update storyshot
- Update cypress image snapshot

**Acceptance Test (how to verify the PR)**

- Go to [this story](https://deploy-preview-3561--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table-user-view-management--with-user-view-management)
- Choose any option in the `Select` column filter (combo box)
- Try to resize `Select` column
- Verify that value in the combo box field truncates
- Verify that min width for the column is `120px`

**Regression Test (how to make sure this PR doesn't break old functionality)**

- tests here

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

**Comment by davidicus** [comment]
Not sure where that min width is being applied. I was looking around the styles and could not see it. As you can see from the image the Entire table column is below the state min width size of 120
image

**Comment by erzhan-temir-mamyrov** [comment]
@davidicus I am wondering if you use some particular knob setups for this story? I couldn't reproduce column being resized to less than 125px.

https://user-images.githubusercontent.com/112560065/192545346-7cb4671e-6eab-48ee-85fc-75f0176af5a1.mov

**Comment by davidicus** [comment]
@erzhan-temir-mamyrov I just manually adjusted the column sizes

**Comment by davidicus** [comment]
this is not exactly at 120 px but it fixes the issue with the dropdown and x being covered in the UI.

**Review by davidicus — APPROVED** [review]

**Pull request merged**
