### PR TITLE
fix(imagecard): enforce maxsize on upload

### PR DESCRIPTION
**Pull request by scottdickerson**
Prereqs #1875 

**Summary**

- fix(ImageCard): add a maxFileSizeInBytes property and enforce it if the image is too large with an error

**Acceptance Test (how to verify the PR)**

- Verify that if you try and upload a file larger than a MB you see the error message

### CODE REVIEW

**Review by tay1orjones — APPROVED** [review]
Looks good once #1875 is in 👍

**Review by JoelArmendariz — APPROVED** [review]
LGTM

**Pull request merged**
