### PR TITLE
1753 hot spot editor modal

### LINKED ISSUE #1753: [Component Proposal] HotSpotEditorModal
Part of issue #1741 

### What package is this for?

- [x] React
- [ ] Angular

### Summary

Dashboard card editor needs to have a support to add hotspots as part of the edit flow for ImageCards. 

Invision prototype found [here](https://ibm.invisionapp.com/share/QBO0RHWV9AE#/screens/319806855)

This feature will be delivered by a storybook example story and the following new components:
- ColorDropdown #1761 
- HotspotTooltipTab #1766
- HotspotDataSourceTab #1767
- HotspotTextStyleTab #1768
- TextHotspot #1861 
- ImageHotspots - add selecting and click creation of hotspots #1770

### Todos
The current [PR](https://github.com/carbon-design-system/carbon-addons-iot-react/pull/1891) contains a complete implementation but there are some issues still open based on feedback and realisations:

- [ ]  make tooltip stay open during hotspot edit (#1895)
- [ ] fix bug where scrollbar in modal causes incorrect position when creating a new hotspot (#1896)
- [ ] UX improvements to adding new hotspots (#1897)
- [ ] Add state handler unit tests (#1898)
- [ ] Improve how thresholds are managed in the cardConfiguration (#1899)
- [ ] Implement the updated design of the thresholds editing (#1769)

### PR DESCRIPTION
**Pull request by bjornalm**
Closes #1753

**Summary**
A new component that ties the pieces together for #1753 except for #1769 which has gotten a new design.

**Change List (commits, features, bugs, etc)**
- added component HotspotEditorModal
- created custom stateHook for the modal
- added component DynamicHotspotSourcePicker
- created storybook exampless
- added unit tests
- Added mousedown fix to imagehotspots
- Added icons to ImageHotspots
- Modification to HotspotTextStyleTab.jsx to better fit the HotspotEditorModal
- Modification to HotspotEditorTooltipTab.jsx to better fit the HotspotEditorModal
- added fullScreen option to composed modal

**Acceptance Test (how to verify the PR)**
https://deploy-preview-1891--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-experimental-hotspoteditormodal--empty

### CODE REVIEW

**Review by scottdickerson — APPROVED** [review]
LGTM, found a few issues during testing that Bjorn is fixing

**Review by tay1orjones — APPROVED** [review]

**Pull request merged**
