### PR TITLE
feat(barchartcard): add maximum data points field

### LINKED ISSUE #3663: [BarChartCardFormSettings][TableCardFormSettings] add maximumDataPoints input
### What package is this for?

- [x] React
- [ ] Angular

### Summary

add `maximumDataPoints` input  similar to the time series card to reduce the amount of data received from the backend
Example: 
image

We can manually add it from the JSON editor now. But its good to add this field in settings tab

Bar card
image
Table card
image

### PR DESCRIPTION
**Pull request by erzhan-temir-mamyrov**
Closes #3663 

**Summary**

- Add number input field for maximum data points

**Change List (commits, features, bugs, etc)**

- Add `maximumDataPoints` property to card editor
- Add unit test
- Update snapshots

**Acceptance Test (how to verify the PR)**

- Go to [this story](https://deploy-preview-3753--carbon-addons-iot-react.netlify.app/?path=/story/2-watson-iot-experimental-%E2%98%A2%EF%B8%8F-dashboardeditor-%E2%98%A2%EF%B8%8F-cardeditor--for-bar-chart)
- Open "Settings" tab
- Change value of "Maximum data points" field
- Verify applied changes in the "Action" tab

**Regression Test (how to make sure this PR doesn't break old functionality)**

- tests here

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

**Review by jessieyan — COMMENTED** [review]
Can you take a look and see if we need to show `maximumDataPoints` in the json editor.

image

**Comment by erzhan-temir-mamyrov** [comment]
@jessieyan I've checked the content of JSON configuration and it depends on `cardConfig` prop. For example, I tried to add maximumDataPoints to card config prop in [this story](https://deploy-preview-3753--carbon-addons-iot-react.netlify.app/?path=/story/2-watson-iot-experimental-%E2%98%A2%EF%B8%8F-dashboardeditor-%E2%98%A2%EF%B8%8F-cardeditor--for-bar-chart), then its field in displayed in JSON editor.

**Review by jessieyan — APPROVED** [review]
Looks good

**Comment by jessieyan** [comment]
@herleraja Hello Amritha, would you please also have a review?

**Review by herleraja — APPROVED** [review]
LGTM

**Pull request merged**
