### PR TITLE
2879 dashboard grid visual regression tests

### LINKED ISSUE #2879: [DashboardGrid] visual regression tests

### PR DESCRIPTION
**Pull request by kevinsperrine**
Closes #2879 

**Summary**

- Adds visual regression testing to all variations of breakpoints and cards.

**Change List (commits, features, bugs, etc)**

- Adds VRT to DashboardGrid

**Acceptance Test (how to verify the PR)**

- Just double check we're not missing variations on features used by the cards.

**Regression Test (how to make sure this PR doesn't break old functionality)**

- n/a

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

**Comment by davidicus** [comment]
> Wow, how many MB are all the images? I thought we would only use a few screenshots in total for our e2e testing considering binary data cannot not be diffed by git (i.e. repo size will keep increasing when we update the images).

Yes, I was thinking we would have one pic with all the cards in one shot. We can discuss if this is not possible.

**Comment by kevinsperrine** [comment]
> > Wow, how many MB are all the images? I thought we would only use a few screenshots in total for our e2e testing considering binary data cannot not be diffed by git (i.e. repo size will keep increasing when we update the images).
> 
> Yes, I was thinking we would have one pic with all the cards in one shot. We can discuss if this is not possible.

One pic with everything isn't possible, because it causes out-of-memory errors when running, so I split them into an image for each card, BUT I'm also including every breakpoint size here, too, so that would drop it a lot if we only included one breakpoint.

**Comment by kevinsperrine** [comment]
> > > Wow, how many MB are all the images? I thought we would only use a few screenshots in total for our e2e testing considering binary data cannot not be diffed by git (i.e. repo size will keep increasing when we update the images).
> > 
> > 
> > Yes, I was thinking we would have one pic with all the cards in one shot. We can discuss if this is not possible.
> 
> One pic with everything isn't possible, because it causes out-of-memory errors when running, so I split them into an image for each card type, BUT I'm also including every breakpoint size here, too, so that would drop it a lot if we only included one breakpoint.

@davidicus What do you want to do here?

**Comment by davidicus** [comment]
I

> > > > Wow, how many MB are all the images? I thought we would only use a few screenshots in total for our e2e testing considering binary data cannot not be diffed by git (i.e. repo size will keep increasing when we update the images).
> > > 
> > > 
> > > Yes, I was thinking we would have one pic with all the cards in one shot. We can discuss if this is not possible.
> > 
> > 
> > One pic with everything isn't possible, because it causes out-of-memory errors when running, so I split them into an image for each card type, BUT I'm also including every breakpoint size here, too, so that would drop it a lot if we only included one breakpoint.
> 
> @davidicus What do you want to do here?

I think we need these for the dashboard. If any can be combined it would be great.

**Comment by kevinsperrine** [comment]
> I
> 
> > > > > Wow, how many MB are all the images? I thought we would only use a few screenshots in total for our e2e testing considering binary data cannot not be diffed by git (i.e. repo size will keep increasing when we update the images).
> > > > 
> > > > 
> > > > Yes, I was thinking we would have one pic with all the cards in one shot. We can discuss if this is not possible.
> > > 
> > > 
> > > One pic with everything isn't possible, because it causes out-of-memory errors when running, so I split them into an image for each card type, BUT I'm also including every breakpoint size here, too, so that would drop it a lot if we only included one breakpoint.
> > 
> > 
> > @davidicus What do you want to do here?
> 
> I think we need these for the dashboard. If any can be combined it would be great.

@davidicus @bjornalm I stripped this down to just the `lg` breakpoint. That makes it 9 files (one for each card type with all sizes) and < 2MB.

**Review by davidicus — APPROVED** [review]

**Review by bjornalm — APPROVED** [review]

**Pull request merged**
