### PR TITLE
fix: add script to automatically sync styles from react

### PR DESCRIPTION
**Pull request by cal-smith**
**Summary**

This PR adds a script to sync the styles from `carbon-addons-iot-react` over to `@ai-apps/styles`. The script is intended to be run manually, with the changes reviewed to prevent inconsistencies. This PR also includes an update to `@ai-apps/styles` with the latest changes from `carbon-addons-iot-react`.

This is the first part of the Cards work for the Angular package.

**Acceptance Test (how to verify the PR)**

- verify that the styles and import paths are correct, builds pass, and repo functionality isn't impacted.

### CODE REVIEW

**Review by davidicus — APPROVED** [review]
Looks good. Not sure why test are failing though.

**Comment by cal-smith** [comment]
> Looks good. Not sure why test are failing though.

The tests are fine, netlify just seems to be upset for some reason

**Comment by cal-smith** [comment]
> > Looks good. Not sure why test are failing though.
> 
> The tests are fine, netlify just seems to be upset for some reason

And now it's happy again ¯\\\_(ツ)_/¯

**Review by sstone2423 — APPROVED** [review]
Everything looks to be passing and storybook seems to be working correctly

**Pull request merged**
