### PR TITLE
fix(progressindicator): add title attribute for text ellipsis

### PR DESCRIPTION
**Pull request by sstone2423**
**Summary**

- Adds a title attribute to the ProgressIndicator step labels so that the user can hover over the ellipsis and see the hidden text for long strings

**Change List (commits, features, bugs, etc)**

- Updated the tests to reflect the change
- Swapped the label element to a span from a p element as its only a label

**Acceptance Test (how to verify the PR)**

- Go to /?path=/story/watson-iot-progressindicator--presentation-vertical and hover over the first step's label that is very long. You should see a tooltip on hover of the full text

**Regression Test (how to make sure this PR doesn't break old functionality)**

- Tests should still pass

### CODE REVIEW

**Review by kevinsperrine — APPROVED** [review]
LGTM. I don't know if the change from a `p` tag to a `span` tag causes any xpath issues for down-stream testing though. @davidicus?

**Comment by sstone2423** [comment]
Solid point. I can swap it back if so

**Review by herleraja — APPROVED** [review]
LGTM

**Comment by davidicus** [comment]
> Solid point. I can swap it back if so @kevinsperrine

Yeah. Unfortunately, until we get al the test IDs in place and everyone can stop using xpath we have to be careful with markup changes. Let's switch that back and this will be good to go.

**Review by davidicus — APPROVED** [review]

**Pull request merged**
