### PR TITLE
fix(valuecard): fix positioning of icons and color of trending secondary values

### LINKED ISSUE #2060: [ValueCard] Layout for value card has been broken
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

ValueCard layout does not match the spec or the old implementation. Redo styles to align with the modern spec

### To Reproduce

1. Go to https://next.carbon-addons-iot-react.com/?path=/story/watson-iot-valuecard--small-thresholds-number-icon
2. See value card icon is not in the proper place

New [dashboard guidance](https://pages.github.ibm.com/ai-applications/design/patterns/dashboards-v2/overview/#value-cards) has the right layout specs

### PR DESCRIPTION
**Pull request by kevinsperrine**
Closes #2060 

**Summary**

- Move the icon beside the label instead of below the value
- Fix the spacing and coloring of the trending values

**Change List (commits, features, bugs, etc)**

- minor fix for rulebuilder story
- bring valuecard design into alignment with designs

**Acceptance Test (how to verify the PR)**

- The https://deploy-preview-2087--carbon-addons-iot-react.netlify.app?path=/story/watson-iot-🚫-dashboard--only-value-cards story should now show the icons to the left of the label on cards with an icon, and the trending values should be vertically aligned and be green or red respectively compared with what is currently on [next](https://next.carbon-addons-iot-react.com/?path=/story/watson-iot-%F0%9F%9A%AB-dashboard--only-value-cards)

### CODE REVIEW

**Comment by scottdickerson** [comment]
I'm still seeing trends below in this story
image

**Comment by kevinsperrine** [comment]
> I'm still seeing trends below in this story @kevinsperrine
> https://deploy-preview-2087--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-valuecard--small-trend-up

@scottdickerson Yep, that's correct. Trends are still below but now colored red/green accordingly and the icons now above like shown in the `"Tightest" Rendering (1057px width)` section. Sorry, I should have split those two descriptions to make it clearer.

Screen Shot 2021-03-03 at 3 03 27 PM

Spec Image: 
Screen Shot 2021-02-19 at 12 47 19 PM

**Comment by sstone2423** [comment]
There was just a major design change to this card. Could we get confirmation from @CynZhang and @dianatran18 that is the layout we want to stick with?
https://github.com/carbon-design-system/carbon-addons-iot-react/pull/1942

**Comment by dianatran18** [comment]
Confirmed that what @kevinsperrine has is correct.

**Review by sstone2423 — APPROVED** [review]

**Review by davidicus — APPROVED** [review]

**Comment by CynZhang** [comment]
the UI update looks good to me.

**Pull request merged**
