### PR TITLE
fix(table): resizable table handles window width changes

### LINKED ISSUE #1974: [Table] Column resize broken is table width changes
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

The Table component seems to take a snapshot of column widths on first render. If you change the width of the table after that, then resizing the columns doesn't size them to match your cursor position. In extreme cases the columns "freak out" and gets super huge, crushing other columns.

This affects tables with `props.options.hasResize = true` and a fluid width.

### To Reproduce

- Make a Chrome window half width of the screen.
- View this Storybook: https://carbon-addons-iot-react.com/?path=/story/watson-iot-table--with-resize-and-initial-column-widths-on-simple-stateful-with-row-selection-sort
- Maximize the window to full screen.
- Resize the columns. Ouch.

### Environment/versions:

- OS: all
- Browser: all
- `carbon-addons-iot-react` version: 2.98.0 (at least)

### Specific timeline issues / requests

This is a regression compared the the current (non-PAL) table components being used in my app. Ideally this should be fixed before the next release (about 6 months time).

### PR DESCRIPTION
**Pull request by bjornalm**
Closes #1974

**Summary**
Added fix to make sure table columns can be manipulated (resized, hidden, shown) after the window has been resized. The main scenario solution is to add an "expander column" that grows and shrinks when a resizable table is resized.  For scenarios with `useAutoTableLayoutForResize` (i.e. resizable columns + table-layout:auto) where the browser resizes all the columns automatically there will be no expander column and we use a window resize listener to keep the actual column sizes and react code sizes in sync.

This PR also solved #1019

**Change List (commits, features, bugs, etc)**
- added expander column to grow and shrink for resizable tables (unless the table uses `useAutoTableLayoutForResize` which makes resizing of all columns automated)
- added window resize listener for resizable tables with `useAutoTableLayoutForResize`. Resize listener measures columns when the window is resized. 
- tested all storybook scenarios 
- added test cases
- added role and aria-label to resize handle for better UI and easier testing
- added dev dependency @testing-library/react-hooks to help with hook testing

**Acceptance Test (how to verify the PR)**
1. Test story from the issue and make sure the bug does not appear. Verify that column resize works. https://deploy-preview-2306--carbon-addons-iot-react.netlify.app?path=/story/watson-iot-table--with-resize-and-initial-column-widths-on-simple-stateful-with-row-selection-sort 
2. Test a story with resizable columns + initial column widths.  Verify that each column gets the width assigned and that resizing the browser grows and shrinks the expander column and not the real columns. Verify that column resize works.  https://deploy-preview-2306--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-table--with-resize-and-initial-column-widths-on-simple-stateful-with-row-selection-sort
3. Test a story with resizable columns that do not have initial widths. Verify that column resize works. Verify that the expander column doesn't occupy any space before the browser window is resized.   https://deploy-preview-2306--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-table--stateful-example-with-expansion-max-pages-and-column-resize
4. Testa a story with resizable columns but that also has `useAutoTableLayoutForResize`. Make sure resizing works. Verify that all columns are resized when the browser is resized. Verify that there is no expander column. https://deploy-preview-2306--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-table--with-resize-and-no-initial-column-width-and-auto-adjusted-column-widths
5. Test a story without column resize and make sure it behaves like normal, i.e. columns are resized when the browser window is resized. https://deploy-preview-2306--carbon-addons-iot-react.netlify.app?path=/story/watson-iot-table--stateful-example-with-every-third-row-unselectable

**Regression Test (how to make sure this PR doesn't break old functionality)**
Try **all** (sorry) different table stories to make sure they look and act fine on render and on window resize. Only the last column should be resized for stories with `hasResize` unless `useAutoTableLayoutForResize` is used (which is only one story).

### CODE REVIEW

**Review by kevinsperrine — COMMENTED** [review]
This works great almost everywhere, but I am running into some issues resizing the "expander" after hiding/showing columns in the table. We changed the behavior of this due to a bug report opened while you were out (see  #2061). It now auto-distributes the space available to all columns rather than trying to reinsert the column with the same width as when it was removed. The "expander" column seems to fail to resize correctly after columns have been removed and re-added. 

This is from https://deploy-preview-2306--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-table--stateful-example-with-expansion-max-pages-and-column-resize.

expandable-column-resize

**Comment by bjornalm** [comment]
> This works great almost everywhere, but I am running into some issues resizing the "expander" after hiding/showing columns in the table. We changed the behavior of this due to a bug report opened while you were out (see #2061). It now auto-distributes the space available to all columns rather than trying to reinsert the column with the same width as when it was removed. The "expander" column seems to fail to resize correctly after columns have been removed and re-added.
> 

Good catch. Looks like this bug already exists in 'next', i.e. resizing fails after **all** columns are first hidden and then (some are) shown again. This is bug has probably been there for a while is unrelated to the current changes. I would suggest that we open a new issue to fix that problem.

**Comment by kevinsperrine** [comment]
> > This works great almost everywhere, but I am running into some issues resizing the "expander" after hiding/showing columns in the table. We changed the behavior of this due to a bug report opened while you were out (see #2061). It now auto-distributes the space available to all columns rather than trying to reinsert the column with the same width as when it was removed. The "expander" column seems to fail to resize correctly after columns have been removed and re-added.
> 
> Good catch. Looks like this bug already exists in 'next', i.e. resizing fails after **all** columns are first hidden and then (some are) shown again. This is bug has probably been there for a while and is unrelated to the current changes. I would suggest that we open a new issue to fix that problem.

Perfect.

**Review by kevinsperrine — APPROVED** [review]

**Comment by kevinsperrine** [comment]
Great work!

**Comment by davidicus** [comment]
> > This works great almost everywhere, but I am running into some issues resizing the "expander" after hiding/showing columns in the table. We changed the behavior of this due to a bug report opened while you were out (see #2061). It now auto-distributes the space available to all columns rather than trying to reinsert the column with the same width as when it was removed. The "expander" column seems to fail to resize correctly after columns have been removed and re-added.
> 
> Good catch. Looks like this bug already exists in 'next', i.e. resizing fails after **all** columns are first hidden and then (some are) shown again. This is bug has probably been there for a while and is unrelated to the current changes. I would suggest that we open a new issue to fix that problem.

Has this bug been opened?

**Review by davidicus — APPROVED** [review]
This PR looks good. Let's open the bug to track the issue mentioned in the thread

**Comment by bjornalm** [comment]
> > > This works great almost everywhere, but I am running into some issues resizing the "expander" after hiding/showing columns in the table. We changed the behavior of this due to a bug report opened while you were out (see #2061). It now auto-distributes the space available to all columns rather than trying to reinsert the column with the same width as when it was removed. The "expander" column seems to fail to resize correctly after columns have been removed and re-added.
> > 
> > 
> > Good catch. Looks like this bug already exists in 'next', i.e. resizing fails after **all** columns are first hidden and then (some are) shown again. This is bug has probably been there for a while and is unrelated to the current changes. I would suggest that we open a new issue to fix that problem.
> 
> Has this bug been opened?

Yes it was opened when it was discovered. Perhaps I should have linked it from this PR for clarity. Here it is
https://github.com/carbon-design-system/carbon-addons-iot-react/issues/2340

**Pull request merged**
