### PR TITLE
feat: upgrade @carbon/charts

### LINKED ISSUE #3169: [carbon-charts] upgrade to version 0.53.5 or later
### What package is this for?

- [x] React
- [ ] Angular

### Summary

Upgrade carbon-charts to version 0.53.5 or later.

**Additional context** 

Needed for Health story -> https://github.ibm.com/maximo/Asset-Health-Insight/issues/8035

### Specific timeline issues / requests

Needed for Health 8.5 release (Feb).

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

_Carbon add-ons for Watson IoT is a collaborative system. We encourage teams to
build components and submit them for integration._

### PR DESCRIPTION
**Pull request by kevinsperrine**
Closes #3169 

**Summary**

- Upgrades to the newest version of @carbon/charts

**Change List (commits, features, bugs, etc)**

- Upgrades to the newest version of @carbon/charts

**Acceptance Test (how to verify the PR)**

- check charts in storybook to ensure no issues

**Regression Test (how to make sure this PR doesn't break old functionality)**

- check charts in storybook to ensure no issues

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

**Comment by davidicus** [comment]
Seems like we have the chart toolbar coming through on this now.
image

**Comment by kevinsperrine** [comment]
> Seems like we have the chart toolbar coming through on this now.

@davidicus, I didn't realize they added it there, too, now. I've already disabled it. Just waiting on checks and preview.

**Comment by davidicus** [comment]
image

# Compared to next

image

**Review by davidicus — APPROVED** [review]
Just the one issue with sizing on the pie chart. Otherwise looks good.

**Comment by kevinsperrine** [comment]
> Just the one issue with sizing on the pie chart. Otherwise looks good.

Yeah, I think that was related to the toolbar, too. The deploy preview matches now.

**Review by bjornalm — APPROVED** [review]
All charts looking good!

**Pull request merged**
