### PR TITLE
refactor(repo): remove vulnerable polished library, clean up other un-used deps

### LINKED ISSUE #3050: Use of a vulnerable version of polished npm package
The package `polished@^2.3.3` is used as the dependency. This version is vulnerable to the ReDoS described here: https://security.snyk.io/vuln/SNYK-JS-POLISHED-1298071

Vulnerability is fixed in versions 3.7.2, 4.1.3 or higher.

### PR DESCRIPTION
**Pull request by kevinsperrine**
Closes #3050 

**Summary**

`polished` is a helper library for styled-components that wasn't used anymore, so I thought I'd check if there were other things that aren't used anymore or other ways we could clean up the repo a bit.

**Change List (commits, features, bugs, etc)**

- `mockdate` is only used in tests -- switched to devDep
- `polished` isn't used at all -- removed. It was originally added as a helper to styled-components years ago, but isn't used anywhere now.
- `react-transition-group` isn't used at all -- removed. It was originally added years ago but has since been removed.
- update all references to `/lib/` to `/es/` in carbon packages (icons mainly)
- `fbjs` removed -- I completely removed it, and didn't have any issues with linking it locally with using `"carbon-addons-iot-react": "link:../../pal-build"` in the package.json (pal-build is a directory containing the built files copied into it), but it was only added back in April https://github.com/carbon-design-system/carbon-addons-iot-react/pull/2276, so I'd like for @scottdickerson to smoke-test this for us, but it's passing in the CI build test.
- `downshift` isn't used. removed. It was originally added when smoke-testing an old carbon upgrade, but it's a dependency of carbon, so we don't need to explicitly include it or pin the version. https://github.com/carbon-design-system/carbon-addons-iot-react/pull/1462
- `lodash` - replace `lodash` with `lodash-es`. @carbon/charts uses `lodash-es`, so instead of having consumed applications have both, this makes them only build with one. This was a pretty automated replacement using a regex search and replace, and then running `eslint --fix` and `yarn format` to pretty it up. Added the custom eslint rule to point people toward `lodash-es` instead.

| Current with `lodash` | After Switch to `lodash-es` |
| ----- | ----- |
| Screen Shot 2021-11-18 at 8 32 53 AM | Screen Shot 2021-11-18 at 8 07 14 AM |

**Acceptance Test (how to verify the PR)**

- confirm removed packages have no affect

**Regression Test (how to make sure this PR doesn't break old functionality)**

- `fbjs` could potentially cause issues with local linking, so we need to test that thoroughly

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

**Review by davidicus — APPROVED** [review]
This is great work! I would say if the build and deploy test works in our CI then we are able to successfully link the package even with the removal of the `fbjs` but since @scottdickerson added and was having issues we should wait for some confirmation or clarification from him.

**Review by bjornalm — APPROVED** [review]
Looks good ot me, nice clean up!

**Comment by davidicus** [comment]
hey @scottdickerson. Do you have a moment to check this PR?

**Comment by scottdickerson** [comment]
if a local `yarn link` from a downstream project worked for you @davidicus then we're good I think

**Comment by davidicus** [comment]
> if a local `yarn link` from a downstream project worked for you @davidicus then we're good I think

Yes, we `yarn link` in our test app that we build in our github actions so we should be good.

**Pull request merged**
