### PR TITLE
fix(table): preserve whitespace in cells with multiple spaces

### LINKED ISSUE #3011: [statefulTable] Extra Spaces are truncated in a text input
### What package is this for?

- [ y] React
- [ ] Angular

### Describe the bug
within the InitialView of statefulTable, extra spaces are truncated (even between the characters). with the editMode, it looks good.
https://carbon-addons-iot-react.com/?path=/story/1-watson-iot-table-table--basic-table-with-full-row-edit-example
provided the screenshots. 1. Edit mode.. 2. View mode.
Tried rendering at cell level, it still happens. 
image
image

### To Reproduce: 
create a statefulTable or use the link : https://carbon-addons-iot-react.com/?path=/story/1-watson-iot-table-table--basic-table-with-full-row-edit-example
Edit a text Input field and provide the value "1  3     6"  click on DONE, and in view mode, the text Input displays "1 3 6".
When you click on Edit again, it restores the correct value to "1  3     6"

1. Go to 'https://carbon-addons-iot-react.com/?path=/story/1-watson-iot-table-table--basic-table-with-full-row-edit-example'
2. Click on 'Edit'
3. Enter any value with extra spaces 
4. Click Done. 
4. See display

> Please create a reduced test case in CodeSandbox:
> https://codesandbox.io/s/github/carbon-design-system/carbon-addons-iot-react/tree/next/packages/react/examples/codesandbox

### Expected behavior

Extra spaces needs to be restored even in the view mode. When click Done, text field should display "1  3     6"

### Environment/versions:

- OS: [e.g. MacOS, Windows]
- Browser: [e.g. chrome, safari]
- `carbon-addons-iot-react` version: [e.g. `v2.60.0`]

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?
yes 
_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### PR DESCRIPTION
**Pull request by kevinsperrine**
Closes #3011 

**Summary**

- adds a class setting `white-space: pre` in table cells that have multiple continuous spaces, so that whitespace is preserved in those cells.

**Change List (commits, features, bugs, etc)**

- add `iot--table__cell-text--preserve` class
- set class in TableCellRenderer when preserveCellWhiteSpace prop is true
- add tests to confirm

**Acceptance Test (how to verify the PR)**

- Go to the table with full rowEdit example
- turn on preserveCellWhiteSpace knob
- edit the first row and add numbers with multiple spaces in the number column
- save
- confirm your multiple spaces are still visible in the output and whitespace is preserved.

**Regression Test (how to make sure this PR doesn't break old functionality)**

- no adverse effects on other strings

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

**Review by bjornalm — COMMENTED** [review]
Code looks good, can't test the preview though. Do you think everyone wants this behaviour? I can imagine that there is a good reason for `white-space: pre` not being the default setting for white-space in general. Perhaps the best option is to put it behind a prop?

**Comment by kevinsperrine** [comment]
> Code looks good, can't test the preview though. Do you think everyone wants this behaviour? I can imagine that there is a good reason for `white-space: pre` not being the default setting for white-space in general. Perhaps the best option is to put it behind a prop?

That's a good thought. That's why I used double spaces as the boolean check, but a prop probably makes more sense. I'll add that.

**Comment by kevinsperrine** [comment]
> Code looks good, can't test the preview though. Do you think everyone wants this behaviour? I can imagine that there is a good reason for `white-space: pre` not being the default setting for white-space in general. Perhaps the best option is to put it behind a prop?

@bjornalm Just pushed the code with the prop added. Hopefully, netlify completes this time. 🤞

**Review by bjornalm — APPROVED** [review]
Nice work

**Review by davidicus — APPROVED** [review]

**Pull request merged**
