### PR TITLE
docs(table): add sorting story and create improved mdx

### LINKED ISSUE #3245: [Table] create story for sorting
### What package is this for?

- [x] React
- [ ] Angular

### Summary

Create story for Table sorting and link and fix the docs. Part of #2820 

**Additional context** Add any other context or screenshots about the feature
request here.

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

_Carbon add-ons for Watson IoT is a collaborative system. We encourage teams to
build components and submit them for integration._

### PR DESCRIPTION
**Pull request by bjornalm**
Closes #3245

**Summary**

Created story and mdx files for table sorting

**Change List (commits, features, bugs, etc)**
- created new sort story and removed old ones
- updated the sort documentation and put it in separate mdx file
- added sort example code for normal Table
- modified getTableKnobs so that it could be used to load just a subset of the knobs with per knob configurable default

**Acceptance Test (how to verify the PR)**

1. Test story https://deploy-preview-3251--carbon-addons-iot-react.netlify.app?path=/story/1-watson-iot-table--with-sorting
2. Go through the related docs

**Regression Test (how to make sure this PR doesn't break old functionality)**

- The table playground story is still working as expected https://deploy-preview-3251--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table--playground

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

**Review by davidicus — APPROVED** [review]
Nice work on these docs!

**Review by kevinsperrine — COMMENTED** [review]
The docs are amazing and everything looks good. I'm trying to figure out if all the new knobs being turned on by default in the playground is intentional, because the playground story in this PR looks much different than what's currently on next. I noticed it, because the hasMultiSort knob isn't working correctly in this PR, but I'm not sure why. My guess is a conflict with another knob that's now on, because it's working in next.

| PR | next |
| -- | -- |
| https://deploy-preview-3251--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table--playground | https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-table--playground |
| In this PR, when enabling multi-sort, sorting the Select column ascending it shows no data | It works as expected in next |

**Comment by bjornalm** [comment]
> The docs are amazing and everything looks good. I'm trying to figure out if all the new knobs being turned on by default in the playground is intentional, because the playground story in this PR looks much different than what's currently on next. I noticed it, because the hasMultiSort knob isn't working correctly in this PR, but I'm not sure why. My guess is a conflict with another knob that's now on, because it's working in next.
> 
> PR	next
> https://deploy-preview-3251--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table--playground	https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-table--playground
> In this PR, when enabling multi-sort, sorting the Select column ascending it shows no data	It works as expected in next

Thanks! The difference you see between this PR and next is because this PR build is in DEV mode and next is not. I thought it would be best for us to have all knobs enabled by default in DEV (to find bugs and regressions) but for the app developer it would probably be a bit overwhelming so they are (almost) all turned off by default.

The bug you found seems to happen when we enable `hasMultiSort` and `hasAdvancedFilter` at the same time. I will file a separate issue for that.

**Review by kevinsperrine — APPROVED** [review]
Awesome work on all these stories/docs. So much cleaner and clearer!

**Pull request merged**
