### PR TITLE
1861 hotspot add text style hotspots

### LINKED ISSUE #1861: [Hotspot] Add text style hotspots
### What package is this for?

- [x] React
- [ ] Angular

### Summary
As part of https://github.com/carbon-design-system/carbon-addons-iot-react/issues/1753 we need to provide a text based hotspot.

**Additional context** 

- the option allows the user to insert a label text
- able to display metrics and values as part of the label (no tooltip)

image
image
image

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### You will consider this component complete when...

- [ ] It's available as an export of this library
- [ ] Additional criteria you may have [e.g. Fully responsive, Accessible to
      WCAG 2.0, etc.]

### Available extra resources

What resources do you have to assist this effort?

_Carbon add-ons for Watson IoT is a collaborative system. We encourage teams to
build components and submit them for integration._

### PR DESCRIPTION
**Pull request by bjornalm**
Closes #1861

**Summary**
Added text based hotspots. The text hotspots will adjust in height and width depending on the content. The styling of the content can be modified using the hotspot config data.

**Change List (commits, features, bugs, etc)**
_Hotspot_
- Added `type` prop. Can be fixed, text or variable. Text type is represented by a new selectable div that shows all content directly.
- Added text formatting props with default values. The props are modified and pass to the stylesheets as CSS custom properties.
- Added size measurement for text type hotspots so that height and width can be dynamic 
- Updated stylesheets. Part of the HotspotContent styles are overridden here since we need access to properties of the hotspot (size, padding, border etc).
- added unit tests

_HotspotContent_
- added `isTitleEditable` and `onChange` prop
- added title input with autofocus and onBlur to trigger change. A visually hidden version of the text based title is still rendered in order to allow the hotspot to grow in width as the user types in the text field.
- added i18n labels
- added unit tests

_ImageHotspots_
- Added onHotspotContentChanged 
- Added logic to determine when the hotspot title is editable
- Modified the story to show working example

- Created a reusable hexToRgb function since it was used in multiple places now

**Acceptance Test (how to verify the PR)**
Since there isn't much of a spec I recommend playing around with the story by clicking and modifying the titles to make sure it feels okay and looks good.

https://deploy-preview-1874--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-imagehotspots--editable-with-text-hotspot

### CODE REVIEW

**Review by tay1orjones — APPROVED** [review]
Looks good to me. It's worth noting that the interaction model here is brittle and it's very easy to break things 🙃 

funny editable

I know the spec was lacking - this is something we can iterate on to improve through feedback and implementation in Monitor.

**Comment by davidicus** [comment]
> Looks good to me. It's worth noting that the interaction model here is brittle and it's very easy to break things 🙃
> 
> funny editable
> 
> I know the spec was lacking - this is something we can iterate on to improve through feedback and implementation in Monitor.

Also worth noting that when the card moves like that the hotspots are off when you click to add them. Not sure if this is realistic in a dashboard grid but something to look into

**Review by davidicus — APPROVED** [review]

**Pull request merged**
