### PR TITLE
docs: begin storybook v6 migration, run codemods

### LINKED ISSUE #964: [Storybook] refactor stories to use CSF
### Summary

> Storybook’s Component Story Format (CSF) is the recommended way to write stories since Storybook 5.2. [Read the announcement](https://medium.com/storybookjs/component-story-format-66f4c32366df) to learn more about how it came to be.
>
> In CSF, stories and component metadata are defined as ES Modules. Every component story file consists of a required default export and one or more named exports.
>
> CSF (component story format) is intended to replace the `storiesOf` api. 
>
> _&mdash; [Storybook documentation](https://storybook.js.org/docs/formats/component-story-format/)_

Should be a fairly straightforward port, though it will touch every story file and potentially the storyshots as well. 

[There is a codemod available. ](https://github.com/storybookjs/storybook/blob/next/lib/codemod/README.md#storiesof-to-csf)

Carbon's stories that we import use the `storiesOf` API currently. This should be fine as we're already mixing CSF and `storiesOf` in our storybook, but it may affect what order the stories are rendered in the sidebar. It's something to investigate - also Carbon may update to the new format at some point rendering this point moot.

### PR DESCRIPTION
**Pull request by tay1orjones**
Closes #964 

**Summary**

- This is the result of running two codemods provided by storybook:
  - [`add-component-parameters`](https://github.com/storybookjs/storybook/blob/next/lib/codemod/README.md#add-component-parameters)
  - [`storiesof-to-csf`](https://github.com/storybookjs/storybook/blob/next/lib/codemod/README.md#storiesof-to-csf) 
- I have the storybook v6 upgrade/addon-docs #963 in progress on another branch. These changes here are required for the upgrade, I put them in their own PR so it's easier to digest and review. 

**Change List (commits, features, bugs, etc)**

- add `component` parameter to stories
- convert stories from `storiesOf` api to the new [Component Story Format (CSF)](https://storybook.js.org/docs/react/writing-stories/introduction#component-story-format)

**Acceptance Test (how to verify the PR)**

- Validate that the modified stories still work the same in the deploy preview. They should all render as expected, 'show info' pane remain the same, knobs still work, etc.

### CODE REVIEW

**Comment by tay1orjones** [comment]
I've fixed the lint errors

- The `storiesof-to-csf` codemod got tripped up on the deprecation warning stories and inadvertently removed them - I reimplemented them.
- Instead of wrapping stories with React.createElement, the stories are decorated with it via `decorators: [createElement]`
- In some places the warnings for `react/destructuring-assignment` were being swallowed by the storiesOf api. Now that it's gone, I had to add some additional eslint disable comments on those lines.

**Comment by tay1orjones** [comment]
@davidicus I just updated with the latest from `next` - all should be good now. Netlify will take ~10mins to redeploy the deploy preview.

**Review by davidicus — APPROVED** [review]

**Comment by tay1orjones** [comment]
Something that has come to mind - we should not allow `storiesOf` to be imported anymore. I'll add a rule to eslint and include here.

**Comment by tay1orjones** [comment]
The new rule in the eslint config specifically bars imports of `storiesOf`. Here you can see other imports from `@storybook/react` are fine, but the `storiesOf` is flagged.

Screen Shot 2020-10-30 at 3 29 27 PM

**Review by bjornalm — APPROVED** [review]
Looks good, did not find any broken stories.

**Pull request merged**
