### PR TITLE
fix(basetablereducer): fix selecting unselectable items

### LINKED ISSUE #1735: [StatefulTable] Batchactions count includes unselectable items
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

When having a table with `options.hasRowSelection = 'multi'` and unselectable items and selecting all items, the table toolbar will show the full item count, although unselectable items are not selected.

### To Reproduce

1. Create a table with `options.hasRowSelection = 'multi'` and some unselectable items
2. Click on select all in the batch actions
3. The table toolbar will show "<all items count> items selected" instead of "<selectable items count> items selected" while only selecting the selectable items

Stackblitz: https://stackblitz.com/edit/carbon-dummy-gm9txb

### Expected behavior

The toolbar should only count the actually selected items, not all items

### Environment/versions:

- OS: MacOS
- Browser: Chrome, Safari
- `carbon-addons-iot-react` version: `2.140.0-next.7`

### PR DESCRIPTION
**Pull request by jonguenther**
Closes #1735 

**Summary**

- fix `StatefulTable` showing wrong item count (total items) when selecting all items `options.hasRowSelection = 'multi'` to only count actually selectable items
**Change List (commits, features, bugs, etc)**

- fixed `baseTableReducer` to filter for selectable items, and then map their ids

**Acceptance Test (how to verify the PR)**

- Added a test to `StatefulTable.test.jsx` to check that unselectable items will not be selected / counted when clicking `Select all`

### CODE REVIEW

**Review by tay1orjones — COMMENTED** [review]
@jonguenther could you write a small unit test to cover this?

**Review by tay1orjones — APPROVED** [review]
Thanks @jonguenther !

**Review by davidicus — APPROVED** [review]

**Pull request merged**
