### PR TITLE
fix(repo): use es build instead of lib in browser

### LINKED ISSUE #2260: Tree shaking is broken due to wrong "browser" value in package.json
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

https://github.com/carbon-design-system/carbon-addons-iot-react/blob/next/packages/react/package.json

Currently the "browser" property is pointing to a CommonJS module folder, which breaks tree shaking in webpack. The correct value should be  "es/src/index.js". 

```
  "browser": "lib/src/index.js",
  "main": "lib/src/index.js",
  "module": "es/src/index.js",
```

### To Reproduce

This is carbon-addons-iot-react size built from graphite, which is 623KB (after gzip) - all the components not being used in my application are bundled in it. 
image

I manually updated "browser" value to "es/packages/react/src/index.js" in the package.json of carbon-addons-iot-react in my node_modules, then re-run graphite build. Now carbon-addons-iot-react is only 40KB. 
image

Here is the webpack tree shaking documentation https://webpack.js.org/guides/tree-shaking. Refer to the first two bullets. 

image

### Specific timeline issues / requests

If possible, please fix this ASAP. Since our application is a mobile application, this issue significantly impact the performance.

### PR DESCRIPTION
**Pull request by kevinsperrine**
Closes #2260 

**Summary**

- We were using the `lib` build instead of the `es` build in the browser property of `package.json`. This was forcing everything to be included and breaking tree shaking. The test app was 8.08MB when built and analyzed in its current state, but after the es switch it dropped to 2.1MB. 

**Change List (commits, features, bugs, etc)**

- change browser package to use es build

**Acceptance Test (how to verify the PR)**

1. Pull this branch down locally
2. create a new directory to hold the built project ie: `mkdir -p ~/tmp/pal-build`
3. run `yarn build`
4. copy built files to project directory created above: `cp -rf package.json umd scss lib es css ~/tmp/pal-build`
5. move to a fresh directory
6. create a test app: `npx create-iot-react-app pal-test`
7. cd into the test app directory:  `cd pal-test`
8. install the locally linked version of carbon-addons. This must be either a relative path or an absolute path (the `~` will not be expanded), so continuing with the `~/tmp/pal-build` example above it would become `yarn add "carbon-addons-iot-react@link:$HOME/tmp/pal-build"` (on mac)
9. build the test application. `yarn build`
10. use serve to serve the built project and confirm it works. `serve -s build`

Optional:
You can compare the build differences by installing source-map-explorer (`yarn add source-map-explorer` and running it on the built application: `yarn source-map-explorer 'build/static/js/*.js'`.

**Regression Test (how to make sure this PR doesn't break old functionality)**

- consuming applications still work as expected

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

**Review by stuckless — DISMISSED** [review]
I have a vague memory of PAL components changing this value a few months back and it caused build issues for us.  We use a CRA based builds and after consuming the update it broke when did production builds.  I don't recall if this was because of changing the browser field or the main field, but, maybe you can review this history of those groups of lines and see if you can find the issue.

I found the issue I was referring to... https://github.com/carbon-design-system/carbon-addons-iot-react/pull/2026

Can you confirm that a CRA based app both build in dev and production mode with this change.

**Comment by kevinsperrine** [comment]
> I have a vague memory of PAL components changing this value a few months back and it caused build issues for us. We use a CRA based builds and after consuming the update it broke when did production builds. I don't recall if this was because of changing the browser field or the main field, but, maybe you can review this history of those groups of lines and see if you can find the issue.
> 
> I found the issue I was referring to... #2026
> 
> Can you confirm that a CRA based app both build in dev and production mode with this change.

That's correct, @stuckless. The fix in #2026 was to add the browser property to fix your build error. This change points that browser property to use the `es` build of the package instead of lib so that tree-shaking works properly and the bundle size can be reduced greatly for consumers. The detailed steps for approval listed above tests this change against a CRA based app. It built and worked with a BarChartCard, and that's why I included such detailed steps so others can recreate it as a consumer app. Once @bjornalm or @scottdickerson confirms this fix, I'll re-request a review from you.

FYI, we also have an issue slated for September to add this type of build into our CI to catch those types of errors in the future.

**Comment by davidicus** [comment]
I was able to confirm that we could build and start up app for both development and production

**Review by davidicus — APPROVED** [review]

**Review by bjornalm — APPROVED** [review]
App successfully installed and running. Thanks for the clear instructions!

**Pull request merged**
