### PR TITLE
fix(table): auto select the select all checkbox

### LINKED ISSUE #1464: [Table] When all the rows are selected through prop, the 'AllSelected' checkbox isn't checked
### Describe the bug
When all the rows of the table are selected through view.table.selectedIds prop, the 'AllSelected' checkbox isn't automatically checked 

Here's a table where I pass the view.table.selectedIds prop as an array that matches the length the entire table data, but the top checkbox shows unselected

image

### To Reproduce

Simply instantiate a table with props where all the selectedIds that are selectable are selected

```
<CommonTable
        {...this.props}
        lightweight
        columns={tableColumns}
        data={tableData}
        options={{
          hasRowSelection: 'multi',
        }}
        view={{
          table: { selectedIds: selectedDimensions },
        }}
        actions={{
          table: { onRowSelected: onSelect, onSelectAll },
        }}
      />
```

### PR DESCRIPTION
**Pull request by bjornalm**
Closes #1464

**Summary**
This fix automatically checks the checkbox if all rows are selected. If some rows are selected, the checkbox gets the Indeterminate state. 

If the `view.table.isSelectAllSelected` is present as a prop then that value will be used instead and if `view.table.isSelectAllIndeterminate` is present that value will be used. See the unit tests for the exact functionality.

Like I commented in the issue itself:
I question if this really is a bug to be fixed? Since the app actually controls the view.table.isSelectAllSelected like the suggested workaround shows I'm not sure it makes sense to handle this value automatically. With this fix implemented, what is the use case of the view.table.isSelectAllSelected (and possibly view.table.isSelectAllIndeterminate) if those values are automatically calculated? So I think we should go with either

a) Don't add this fix
b) Add this fix and if we don't have a use case for overriding the automatically calculated props view.table.isSelectAllSelected and view.table.isSelectAllIndeterminate then we should probably deprecate them.
c) **CURRENT PR -** We combine view.table.isSelectAllSelected and view.table.isSelectAllIndeterminate with a default automatic behaviour like this issue describes.

**Change List (commits, features, bugs, etc)**
1. Removed the default value "false" for the view.table.isSelectAllSelected 
2. Added automatic calculation for isSelectAllSelected and isSelectAllIndeterminate
3. Added unit tests

**Acceptance Test (how to verify the PR)**
1. Go to story ?path=/story/watson-iot-table--with-multi-select-and-batch-actions
2. Select "Table" from the Type of Table knob
3. Add `row-0,row-1,row-2,row-3,row-4,row-5,row-6,row-7,row-8,row-9` to the selectedIds knob
4. Make sure the "Select all is selected"
5. Play with the combination of `isSelectAllSelected` and `isSelectAllIndeterminate` knobs to make sure they override the automatic behaviour

### CODE REVIEW

**Comment by sstone2423** [comment]
This is an interesting problem. I was recently implementing a NestedTable and was really surprised that addons doesn't provide the selection logic. I think its beneficial to allow the user to implement their own selection logic, but I'd like if addons had a default. As for a regular, non-nested table, I can't think of a reason why a consumer would want to implement their own selectAll logic so I'd vote to deprecate it. It would also help bring down the very high number of prop options we have

**Comment by tay1orjones** [comment]
Something to keep in mind with this is that we have a longstanding request https://github.com/carbon-design-system/carbon-addons-iot-react/issues/124 for rows with child/nested rows to support indeterminate state on the parent when a child row is selected.

It doesn't look like this really blocks that future functionality in any way, but will be an addition to this logic at some point (unless you want to look at it now in conjunction with this)

**Review by sstone2423 — APPROVED** [review]

**Review by tay1orjones — APPROVED** [review]

**Comment by bjornalm** [comment]
> Something to keep in mind with this is that we have a longstanding request #124 for rows with child/nested rows to support indeterminate state on the parent when a child row is selected.
> 
> It doesn't look like this really blocks that future functionality in any way, but will be an modification to this logic at some point (unless you want to look at it now in conjunction with this)

I'll rather keep them separated since I'm already "complicating" this PR with different scenarios on how to handle the fix

**Comment by bjornalm** [comment]
I will create a new issue to deprecate the props `isSelectAllSelected` and `isSelectAllIndeterminate`

**Pull request merged**
