### PR TITLE
Hotifix to Master -- chore(release): disable Travis CI, enable Publish GH action workflow

### PR DESCRIPTION
**Pull request by tay1orjones**
**Summary**

- Travis has been turned off. This pulls the new deploy config through to master so future hotfixes will be published to @latest

### CODE REVIEW

**Review by scottdickerson — APPROVED** [review]
LGTM

**Comment by tay1orjones** [comment]
This will ensure that #1804 gets published once it's merged.

**Review by davidicus — APPROVED** [review]

**Pull request merged**
