### PR TITLE
fix(table): remove extra padding for sortable columns

### LINKED ISSUE #3473: [Datatable] Table row data is needlessly constrained by Up/Down Sort Icon
From https://jsw.ibm.com/browse/GRAPHITE-50211
when there's a table with sortable columns, the displayable area of the column EXCLUDES the vertical space taken up by the Up/Down sort icon.

See attached image... the red arrow points to the icon, and the braces show the area that should be available for displaying column data:

The App Name column has plenty of space to show the value of TECHMOBILE, but it shows "TECHMO...".  If you hover over the column header you will see the Up/Down sort icon appear and see that it is constraining the displayable width of the column text.

### PR DESCRIPTION
**Pull request by jessieyan**
Closes #3473 

**Summary**

- remove extra padding for sortable columns

**Change List (commits, features, bugs, etc)**

- remove the changes introduced in [#2098](https://github.com/carbon-design-system/carbon-addons-iot-react/issues/2098)

**Acceptance Test (how to verify the PR)**

- before
Pasted Graphic

- after
image

**Regression Test (how to make sure this PR doesn't break old functionality)**

- tests here

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

**Review by davidicus — COMMENTED** [review]
I am not seeing a story that has a column aligned to end where I can test if the padding still exist. Am I missing it or can we add one so we can see it working?

**Comment by jessieyan** [comment]
> I am not seeing a story that has a column aligned to end where I can test if the padding still exist. Am I missing it or can we add one so we can see it working?

Yeah, it is  a little tricky to find it. It is in the playground story.  First, you would need to enable sort and then go to **Date Rendering** tab to select align.

image

**Comment by jessieyan** [comment]
I will fix the conflicts.

**Comment by davidicus** [comment]
Ok. I am seeing it now. Unrelated to your changes but part of it. The alignment seems off when you align to the right. Can we fix that here?

**Comment by jessieyan** [comment]
> Ok. I am seeing it now. Unrelated to your changes but part of it. The alignment seems off when you align to the right. Can we fix that here?

Update the spacing to `spacing-07` 2rem. It looks better now.
image

Right-to-left
image

**Review by davidicus — APPROVED** [review]

**Pull request merged**
