### PR TITLE
fix(chartcards): show actual colors in editable state

### LINKED ISSUE #1601: [Chart Cards] show actual colors in isEditable state
### What package is this for?

- [x] React
- [ ] Angular

### Summary

Currently chart cards show the data series (bars, lines), as different shades of gray in the isEditable state. Considering we allow custom colors in both charts, we should show the actual colors so the user can get the preview of what they will actually see

**Additional context**

internal issue: https://github.ibm.com/wiotp/monitoring-dashboard/issues/1363

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

September release

### Available extra resources

What resources do you have to assist this effort?

Myself, hopefully

### PR DESCRIPTION
**Pull request by sstone2423**
Closes #1601

**Summary**

- Chart colors are customizable so we should show the actual current colors to the user so they can preview them

**Change List (commits, features, bugs, etc)**

- Removed `DISABLED_COLORS` from BarChartCard and TimeSeriesCard

**Acceptance Test (how to verify the PR)**

- Go to isEditable story for BarChartCard and TimeSeriesCard and ensure the actual line/bar colors are being shown, but you are not able to see a tooltip on hover or interact with the legend

### CODE REVIEW

**Review by bjornalm — APPROVED** [review]
Nice work, although I have to say I don't understand the old reason for why the isEditable was forcing gray colors.

**Comment by sstone2423** [comment]
> Nice work, although I have to say I don't understand the old reason for why the isEditable was forcing gray colors.

I think it was part of the original design to give a more 'preview' look. The colors weren't customizable originally (I believe)

**Review by marcJV — APPROVED** [review]

**Review by tay1orjones — COMMENTED** [review]
Should the hover state be removed as well (if possible) since there isn't a tooltip or anything else "interactable"?

hover bar

**Review by tay1orjones — APPROVED** [review]
looks good, pending my comment above about the hover state

**Comment by sstone2423** [comment]
@tay1orjones 

> Should the hover state be removed as well (if possible) since there isn't a tooltip or anything else "interactable"?
> 
> hover bar

Unfortunately there is no options provided by carbon charts to disable that hover state. An issue was opened with them: https://github.com/carbon-design-system/carbon-charts/issues/798

I can try to override with styling, but it might be messy

**Comment by tay1orjones** [comment]
@sstone2423 👍  All good then - appreciate you linking the issue! Lets merge this

**Pull request merged**
