### PR TITLE
fix(combo-box): fix scss to not break OptimizeCSSAssets webpack plugin

### LINKED ISSUE #2314: [ComboBox] Negating CSS variables in `calc()` breaks OptimizeCSSAssetsPlugin
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

negating a `var` within `calc` breaks OptimizeCSSAssetsPlugin (which is used by CRA in production builds) with
```
Failed to compile.

Parse error on line 1: 
-var(--cds-...
-^
Expecting "ADD", "SUB", "LENGTH", "ANGLE", "TIME", "FREQ", "RES", "UNKNOWN_DIMENSION", "EMS", "EXS", "CHS", "REMS", "VHS", "VWS", "VMINS", "VMAXS", "PERCENTAGE", "NUMBER", "dimension", got unexpected "FUNCTION"
CompileError: Begins at CSS selector undefined
```
Tracking down the error (which was not easy) finds the following line:
https://github.com/carbon-design-system/carbon-addons-iot-react/blob/c0328c3869cd9b2ecafbc13b3c04f63114e8a8db/packages/react/src/components/ComboBox/_combo-box.scss#L32
This is just the first of many in this particular file (and probably the entire project).
This particular line end up being interpolated into `bottom: calc(-var(--cds-spacing-08, 2.5rem))` since `$ai-apps-combobox-input-height` is `$spacing-08` and `$spacing-08` is `var(--cds-spacing-08, 2.5rem)`.

The best way to handle negating the value is to multiple by -1: https://github.com/css-modules/postcss-icss-values/issues/64#issuecomment-241285628

### To Reproduce

1. create a new app with CRA
2. add ComboBox styles
3. run the production build

_cannot be recreated using codesandbox since it happens during production build_

### Expected behavior

No error is given and the production build produces the correct code.

### Environment/versions:

- OS: MacOS
- Browser: N/A
- `carbon-addons-iot-react` version: 2.144.0

### Additional context

Current workaround, use CRACO remove / disable OptimizeCSSAssetsPlugin (which is not that great...)

### Specific timeline issues / requests

N/A

### PR DESCRIPTION
**Pull request by kevinsperrine**
Closes #2314 

**Summary**

- When using `@console/pal` themes along side `carbon-addons-iot-react` it enables certain feature flags that break webpack builds with OptimizeCSSAssetsPlugin. This adjusts the scss to work correctly in this instance.

**Change List (commits, features, bugs, etc)**

- refactor scss variables to prevent failures in building

**Acceptance Test (how to verify the PR)**

- Can build production builds of the test app when using `@console/pal` package theme, and `combo-box.scss` as detailed in the issue. Instructions for installing `@console/pal` are found in the issue as well. For steps to setup a test app see https://github.com/carbon-design-system/carbon-addons-iot-react/pull/2775

**Regression Test (how to make sure this PR doesn't break old functionality)**

- ComboBox stories remain unchanged.

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

**Review by davidicus — APPROVED** [review]

**Comment by bjornalm** [comment]
The build fails when following the instructions:
image

I tried it twice

**Comment by kevinsperrine** [comment]
> The build fails when following the instructions:
> image
> 
> I tried it twice

🤔  Weird. This is related to the issue @davidicus was talking about with the CI build...not what was happening with the ComboBox code... What version of sass are you using in your "test application"?

**Comment by bjornalm** [comment]
> > The build fails when following the instructions:
> > I tried it twice
> 
> 🤔 Weird. This is related to the issue @davidicus was talking about with the CI build...not what was happening with the ComboBox code... What version of sass are you using in your "test application"?

"1.41.1"

**Comment by davidicus** [comment]
> > > The build fails when following the instructions:
> > > I tried it twice
> > 
> > 
> > 🤔 Weird. This is related to the issue @davidicus was talking about with the CI build...not what was happening with the ComboBox code... What version of sass are you using in your "test application"?
> 
> 1.41.1

Which is the same version as the CLI.

**Comment by kevinsperrine** [comment]
> > > > The build fails when following the instructions:
> > > > I tried it twice
> > > 
> > > 
> > > 🤔 Weird. This is related to the issue @davidicus was talking about with the CI build...not what was happening with the ComboBox code... What version of sass are you using in your "test application"?
> > 
> > 
> > 1.41.1
> 
> Which is the same version as the CLI.

I'm willing to bet [this change](https://github.com/sass/dart-sass/blob/main/CHANGELOG.md#1400) caused it. Released 6 days ago.

**Comment by kevinsperrine** [comment]
@bjornalm @davidicus Added units to clamp to fix that issue, too.

**Review by bjornalm — APPROVED** [review]
Great, all is working now

**Pull request merged**
