### PR TITLE
feat(cardeditor): implementation of the card code editor

### LINKED ISSUE #1563: [CardCodeEditor] enable editing of dashboard card config json
### What package is this for?

- [x] React
- [ ] Angular

### Summary

In support of the dashboard builder/editor #1372, provide a way to edit the card configration json directly through an editor placed in a modal. 
- Per the spec, editor should support fullscreen and truncation through "show more" button. We should be able to utilize the [multi-line CodeSnippet component](https://carbon-addons-iot-react.com/?path=/story/codesnippet--multi-line) for this and use the Monaco editor within.
- On save, the edited JSON should be passed via a callback.

Consuming applications are already using the [Monaco editor](https://github.com/microsoft/monaco-editor), and I believe the [Monaco JSON plugin](https://github.com/microsoft/monaco-json).
- Add Monaco editor as a peer dependency
- Add Monaco JSON plugin as a peer dependency
- Update installation documentation (and the story for this component) to highlight that in order for this to work they must install this dependency. We might also consider editing the default installation instructions on the readme to highlight this. In theory if someone isn't using this component they shouldn't have to install it, but they'll get peer dep warnings in the console.

**Additional context**
image

### PR DESCRIPTION
**Pull request by davidicus**
Closes #1563

**Summary**

A code editor modal that supports code highlighting and language specific intellisense. 

**Change List (commits, features, bugs, etc)**

- Added `monaco-editor/react` npm package.
- Created `CardCodeEditor` component
- Created `_card-code-editor.scss` and added it to `styles.scss`
- Created two new stories for the new component
- Exported `CardCodeEditor` from `index.js`
- Added test for `CardCodeEditor`

**Acceptance Test (how to verify the PR)**

- Go to the new CardCodeEditor stories and play around.

### CODE REVIEW

**Review by stuckless — COMMENTED** [review]
@davidicus this looks like a good addition, although not sure why it is in a dialog vs just an editor component.

I was looking at pulling in Ace Editor, but, since you are pulling in this one, I might look at using the same.

Couple questions...
1. If you exposed an "Editor" component that wrapped much of Manaco, then I wouldn't need add a dependency for it explicitly and that way we could be sure we were using the same copy/version instead of potentially having 2 versions pulled in.
2. Does monaco support gutters where you can attach errors to the gutters?  This was one reason I was looking at Ace, although to be fair, I didn't really look at Monaco, since I've used Ace in the past.

How much of an overhead is monaco-editor going to add to the bundle sizes?  I'm wondering if components like this that tend to bring in a large set of other dependencies should be put into a separate component repo?

**Comment by JordanWSmith15** [comment]
@davidicus Agree that it should be a component by itself, rather than embedded as part of a dialog. I have a use case for this as a 80% section of a page. It seems like it also needs to adopt the height of it's parent (it is blowing out vertically on a small dialog)

**Comment by bryancboyd** [comment]
@davidicus I'm not sure this component needs its own export, especially if we are framing it as a "Card" code editor.

Perhaps there is utility in providing a simple Monaco wrapper, as Jordan suggested, and calling it a CodeEditor?  And CardCodeEditor wraps in a modal, provides callbacks for our custom dashboard card json validation, etc?

I suggest we remove the CardCodeEditor package export and only scope this as being used by the CodeEditor component.

**Comment by bryancboyd** [comment]
This perfectly fits the needs of the Dashboard editor though 👏  looking good

**Comment by davidicus** [comment]
@stuckless @JordanWSmith15 
 
> 1. If you exposed an "Editor" component that wrapped much of Manaco, then I wouldn't need add a dependency for it explicitly and that way we could be sure we were using the same copy/version instead of potentially having 2 versions pulled in.

It is in a dialog because that is what the spec I was building for required. That being said, I can definitely expose an editor component on it's own that I consume here. 
> 2. Does monaco support gutters where you can attach errors to the gutters?  This was one reason I was looking at Ace, although to be fair, I didn't really look at Monaco, since I've used Ace in the past.

Monaco supports a lot of functionality and I believe most of the features that are available with VSCode. I have not see the errors in the gutters along the line numbers but Monaco has it on the scroller or minimap.

image


> How much of an overhead is monaco-editor going to add to the bundle sizes? I'm wondering if components like this that tend to bring in a large set of other dependencies should be put into a separate component repo?

The package itself is about 5.5kB minified + gzipped
https://bundlephobia.com/result?p=@monaco-editor/react@3.6.3

What product is the editor requirement for? I will open up another issue to refactor this into its own component. I would like to add the product tags so we have the context in our priority call. 

@bryancboyd I can remove the export

**Review by bryancboyd — APPROVED** [review]

**Review by tay1orjones — APPROVED** [review]

**Pull request merged**
