### PR TITLE
[PageTitleBar] update style to match new spec

### LINKED ISSUE #1661: [PageTitleBar] update styling to match new spec
### What package is this for?

- [x] React
- [ ] Angular

### Summary

Internal issue: https://github.ibm.com/wiotp/monitoring-dashboard/issues/1363

With the upcoming and in progress DashboardEditor comes a new spec for PageTitleBar.

See specs below for details:

image (1)

image (3)

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

October release

### Available extra resources

What resources do you have to assist this effort?

 I can add this in

### PR DESCRIPTION
**Pull request by sstone2423**
Closes #1661 

**Summary**

- As part of the new DashboardEditor, a new design spec has been created for the header (PageTitleBar). This PR updates the styling to match those new specs

**Change List (commits, features, bugs, etc)**

- Updated styles to match spec
- Updated story to match a common DashboardEditor header
- Changed a deprecated icon in the TileGallery stories to a similar valid icon to remove warning in console

**Acceptance Test (how to verify the PR)**

- Go to each PageTitleBar story and ensure they match the specified design seen in the above issue

### CODE REVIEW

**Review by scottdickerson — APPROVED** [review]
LGTM

**Comment by tay1orjones** [comment]
@sstone2423 is there an internal pal issue for this to document the source of the spec outlined in https://github.com/carbon-design-system/carbon-addons-iot-react/issues/1661?

**Comment by tay1orjones** [comment]
@dianatran18 @lukefirth could you take a look and validate this from a design perspective? [Here's a link to the PageTitleBar stories in the deploy preview](https://deploy-preview-1667--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-pagetitlebar--base)

**Comment by sstone2423** [comment]
@tay1orjones I've added the internal link to the issue and commenting it here: https://github.ibm.com/wiotp/monitoring-dashboard/issues/1363

That issue is mainly about the DashboardEditor, where the PageTitleBar updates are a side effect

**Comment by dianatran18** [comment]
This is good to go on the design side, until we make further changes to the overall page header. 

Thanks!

**Review by tay1orjones — APPROVED** [review]

**Pull request merged**
