### PR TITLE
docs(table): add story and docs for filters

### LINKED ISSUE #3289: [Table] story and docs for filtering
### What package is this for?

- [x] React
- [ ] Angular

### Summary

Create a coherent story for all filtering functionality and update the docs if needed. Part of https://github.com/carbon-design-system/carbon-addons-iot-react/issues/2820

**Additional context** Add any other context or screenshots about the feature
request here.

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

_Carbon add-ons for Watson IoT is a collaborative system. We encourage teams to
build components and submit them for integration._

### PR DESCRIPTION
**Pull request by bjornalm**
Closes #3289

**Summary**
Adds story and updated documentation for filters
(The advanced filter doc section was left unchanged for now since it is experimental and pretty complex) 

**Change List (commits, features, bugs, etc)**
- New story
- Updated mdx
- Small fixes to Table.story.helpers

**Acceptance Test (how to verify the PR)**

- Test the new story https://deploy-preview-3297--carbon-addons-iot-react.netlify.app?path=/story/1-watson-iot-table--with-filtering
- Proof read and check the new mdx section https://deploy-preview-3297--carbon-addons-iot-react.netlify.app?path=/docs/1-watson-iot-table--with-filtering

**Regression Test (how to make sure this PR doesn't break old functionality)**

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

**Review by kevinsperrine — COMMENTED** [review]
Docs all look good and story works as expected, but there's extra space on the right side of the table that I'm not sure where it's coming from...

Screen Shot 2022-02-17 at 11 51 07 AM

**Comment by bjornalm** [comment]
> Docs all look good and story works as expected, but there's extra space on the right side of the table that I'm not sure where it's coming from...
> 
> Screen Shot 2022-02-17 at 11 51 07 AM

It is the column tooltip bug I mentioned in the standup, I filed an issue for it.

**Comment by kevinsperrine** [comment]
> > Docs all look good and story works as expected, but there's extra space on the right side of the table that I'm not sure where it's coming from...
> It is the column tooltip bug I mentioned in the standup, I filed an issue for it.

Got it. I forgot about you mentioning that.

**Review by davidicus — APPROVED** [review]
LGTM once merge conflicts are resolved.

**Pull request merged**
