### PR TITLE
fix bug for removing ID from JSON Editor

### PR DESCRIPTION
**Pull request by EdmondCShaffer**
Closes ##3098
**Summary**

We need to show the ID in the JSON editor. Hiding this is inconsistent with the export feature 

**Change List (commits, features, bugs, etc)**

- items_here

**Acceptance Test (how to verify the PR)**

1. edit any dashboard
2. edit any card
3. Click JSON Editor
4. The json will have the id field.

**Regression Test (how to make sure this PR doesn't break old functionality)**

- tests here

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

**Comment by kevinsperrine** [comment]
> The json will not have the id field.

@EdmondCShaffer I think this is a typo in the acceptance instructions, right? The field _should_ include the ID now where it didn't before, correct?

Screen Shot 2021-12-01 at 10 49 51 AM

**Comment by EdmondCShaffer** [comment]
@kevinsperrine yes that is correct I fixed the typo.

**Comment by bjornalm** [comment]
Is #3140 referring to an internal issue? There is no such issue for this repo.

**Review by bjornalm — APPROVED** [review]
LGTM, just double check that you link to the proper github issue.

**Review by davidicus — APPROVED** [review]

**Pull request merged**
