### PR TITLE
repo: add github actions for testing

### PR DESCRIPTION
**Pull request by tay1orjones**
**Summary**

- Add GitHub Actions workflows to evaluate Actions vs Travis CI

**Change List (commits, features, bugs, etc)**

- Add new GitHub Actions workflows. Each action is individually listed as a status check based on the script that is ran. No more hunting through the dense Travis CI log to see why it failed! 🎉 
  - build.yml
  - format.yml
  - lint.yml
  - test.yml
    - reports coverage to coveralls via their official action!
  - publish.yml
    - This one is just for testing right now, it runs semantic release with `--dry-run`.
- I altered Travis to not run lint/format/test anymore, but it will still be our primary build/publish CI for now and we'll still require the build to pass there before we merge PRs. 
- Fix a badge image in the readme

**Acceptance Test (how to verify the PR)**

- The new actions show up on this PR status checks and show pass/fail

### CODE REVIEW

**Comment by tay1orjones** [comment]
Wow - the performance impact here is very substantial. Because we can run these in parallel, we gain the same amount of confidence as we do from Travis in a fraction of the time. Just based on these initial commits, all checks completed in under 7 minutes. Travis took over 30 minutes to do the same.

**Review by sstone2423 — APPROVED** [review]
Nice!

**Review by bjornalm — APPROVED** [review]
Nice work!

**Review by davidicus — APPROVED** [review]

**Pull request merged**
