### PR TITLE
fix(list): adjust hierarchy indentations to match spec

### LINKED ISSUE #1568: [HierarchyList] invalid indentation padding and arrow direction
Currently Items with no children show up without any indent and are not aligned with items at the same level that do have children, since those are indented for the expand/collapse carat. This implies incorrectly a hierarchical relationship between these items.

Expected behavior is that all items  at the same level will be horizontally aligned. If an item does not have child items it should be indented to match the ones that are indented for carats.

Screenshot shown here:  
(In this situation, Home and My Reports are at the same level as the items below. They should be indented.)

image (2)

### PR DESCRIPTION
**Pull request by tay1orjones**
Closes #1568

**Summary**

- HierarchyList indentation is improved for when there's a mix of category and non-category items.

image

**Change List (commits, features, bugs, etc)**

- Root level items with no children align with items that have children
- Children items have slightly more indentation than their parent
- Flipped the caret direction to be consistent with sidenav and accordion. When the section is closed, the arrow points down.

**Acceptance Test (how to verify the PR)**

- View and validate the new [`HierarchyList \ with mixed hierarchies`](https://deploy-preview-1617--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-experimental-hierarchylist--with-mixed-hierarchies) story
- Check the other HierarchyList stories to ensure no visual regressions

### CODE REVIEW

**Comment by tay1orjones** [comment]
@JessicaGentry @jm986 I went ahead and knocked this out today - let me know if this doesn't meet all your needs.

**Review by sstone2423 — COMMENTED** [review]
Looks good, but beware I recently made this change to single nested hierarchy tables recently as a UX change.

We may need to update tables to also reflect this design change

See this story for an example: https://carbon-addons-iot-react.com/?path=/story/watson-iot-table--stateful-example-with-single-nested-hierarchy

I didn't think to add a row that had no parent category

**Review by sstone2423 — APPROVED** [review]

**Review by marcJV — APPROVED** [review]
Looks good to me

**Pull request merged**
