### PR TITLE
fix(suite-header): truncate long menu item text

### LINKED ISSUE #2221: [AppShell] Strings of the menu items do not truncate
### What package is this for?

- [X] React
- [ ] Angular

### Describe the bug

Translated text strings in ui shell menus do not ellipse 

### To Reproduce

Extend the string in any of the menu items and it cuts off. The menu items will do this in some translations.
image (21)

### Specific timeline issues / requests
MAS 8.5

### PR DESCRIPTION
**Pull request by kevinsperrine**
Closes #2221 

**Summary**

Menu item text wasn't being truncated before.

**Change List (commits, features, bugs, etc)**

- add css change to allow truncate of menu text.
- added long text examples to the "Header with custom action items" story.

**Acceptance Test (how to verify the PR)**

- long text in the help and profile menus of the "Header with custom action items" story should truncate

**Regression Test (how to make sure this PR doesn't break old functionality)**

- no other changes.

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

**Comment by davidicus** [comment]
Is there a way to provide the title so users can have a browser tooltip? I know the content is dynamic but I wonder if we use the child prop

**Comment by kevinsperrine** [comment]
> Is there a way to provide the title so users can have a browser tooltip? I know the content is dynamic but I wonder if we use the child prop

Theoretically, we could, but I would think that would fall on the consumers to pass via the metaData props like I change in the story wouldn't it? https://github.com/carbon-design-system/carbon-addons-iot-react/pull/2662/files#diff-2ea9cb012362ff50d44cc770f39dc595015089e7cac8eb04721d463db7be6d86R174

**Review by bjornalm — APPROVED** [review]
Code looks good.

We could perhaps check for overflow and automatically add the metadata title if it isn't already present? Chances are that the App developers might miss that detail otherwise.

**Comment by kevinsperrine** [comment]
> Code looks good.
> 
> We could perhaps check for overflow and automatically add the metadata title if it isn't already present? Chances are that the App developers might miss that detail otherwise.

That could work. I'll add that in today.

**Comment by kevinsperrine** [comment]
@davidicus @bjornalm Added fallback titles when an item is truncated if they don't exist and tests to confirm.

**Review by davidicus — APPROVED** [review]

**Pull request merged**
