### PR TITLE
fix(sidepanel): not to show tooltip when closed inline

### LINKED ISSUE #3695: [SidePanel] Content of panel can be tabbed to when closed.
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

When the SidePanel is closed you are still able to tab to its contents. The tabbing should not go into content when closed.

### To Reproduce

1. Go to [this story](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-sidepanel--default)
2. Click on isOpen knob to close the panel
3. click in frame and tab twice
4. See tooltip from Title show

> Please create a reduced test case in CodeSandbox:
> https://codesandbox.io/s/github/carbon-design-system/carbon-addons-iot-react/tree/next/packages/react/examples/codesandbox

### Environment/versions:

- OS: [e.g. MacOS, Windows]
- Browser: [e.g. chrome, safari]
- `carbon-addons-iot-react` version: [e.g. `v2.60.0`]

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### PR DESCRIPTION
**Pull request by jessieyan**
Closes #3695

**Summary**

- not able to tab on content when side panel is closed

**Change List (commits, features, bugs, etc)**

- SidePanel.jsx  added `tabIndex` and `aria-hidden`

**Acceptance Test (how to verify the PR)**

- go to side panel [story](https://deploy-preview-3744--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-sidepanel--default)
- uncheck isOpen
- choose `inline`
- click on frame and tab 
- see any tooltip or any content showed up or focused

**Regression Test (how to make sure this PR doesn't break old functionality)**

- tests here

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

**Comment by jessieyan** [comment]
There are some cypress flaky tests failed. This is should be fixed in another [PR](https://github.com/carbon-design-system/carbon-addons-iot-react/pull/3740) in `master`. Will merge it when it's available in `next`.

**Review by herleraja — APPROVED** [review]
LGTM

**Review by davidicus — CHANGES_REQUESTED** [review]
This looks good for the title component but we have to make sure none of the content is able to to be tabbed to when closed. I thought we had an issue for this but I am not able to find one.

**Comment by erzhan-temir-mamyrov** [comment]
LGTM 👍

**Pull request merged**
