### PR TITLE
fix(hierarchy-list): reset page (as necessary) when pageSize changes

### LINKED ISSUE #2918: [HierarchyList] pageSize doesn't reset when not enough items to fill current page
### What package is this for?

- [X] React
- [ ] Angular

### Describe the bug

If the pageSize prop changes while you're on a page higher than the total pages available you get stock on a page and cannot get back to the items.

### Specific timeline issues / request
list-reset-pagination
s

### PR DESCRIPTION
**Pull request by kevinsperrine**
Closes #2918 

**Summary**

- Previously, if you paged through the results to a higher page, but then changed the pagination (or removed it) You could get stuck on the higher page and be unable to get back to the list items.

**Change List (commits, features, bugs, etc)**

- add useEffect to check current page and max page and reset to page 1 if necessary.

**Acceptance Test (how to verify the PR)**

- Go the HierarchyList with large number of items story
- change pageSize to small
- change to page 2
- change pageSize to undefined
- you should return to page 1 with all results

**Regression Test (how to make sure this PR doesn't break old functionality)**

- no adverse effects on other stories

**Things to look for during review**

- [ ] Make sure all references to `iot` or `bx` class prefix is using the prefix variable
- [ ] (React) All major areas have a `data-testid` attribute. New test ids should have test written to ensure they are not changed or removed.
- [ ] UI should be checked in RTL mode to ensure the proper handling of layout and text.
- [ ] All strings should be translatable.
- [ ] The code should pass a11y scans (The storybook a11y knob should show no violations). New components should have a11y test written.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] All components should be passing visual regression test. For new styles or components either a visual regression test should be written for all permutations or the base image updated.
- [ ] Changes or new components should either write new or update existing documentation.
- [ ] PR should link and close out an existing issue

### CODE REVIEW

**Comment by davidicus** [comment]
If you change the knob to page size `xl` then go to page 33 and then change the prop to `lg` the results go back to 0-9 but you remain on page 33. you are still able to go to page 32 and that seems to reset to the right number but def unexpected.

**Review by bjornalm — APPROVED** [review]
Nice work. Perhaps you want to add a unit test for this?

**Comment by kevinsperrine** [comment]
> Nice work. Perhaps you want to add a unit test for this?

Yeah, I'm going to. These are just small issues I've come across adding the virtual list stuff. I'll add the unit tests in that PR when I open it to cover all the basis with both regular and virtual list content.

**Comment by kevinsperrine** [comment]
> If you change the knob to page size `xl` then go to page 33 and then change the prop to `lg` the results go back to 0-9 but you remain on page 33. you are still able to go to page 32 and that seems to reset to the right number but def unexpected.

Adjusted this so that it stays on page 33 and updates the list to show the correct items for page 33.

**Review by davidicus — APPROVED** [review]

**Pull request merged**
